export const DE = {
    Translator: "Übersetzer",
    TranslatorName: "v1rul3nt, Quiipy, Xerex, Wehraboo, JenniferRosebrock",
    Language: "Sprache",
    ThisLanguage: "Deutsch",
    OK: "OK",
    SteelMill: "Stahlwerk",
    StainlessSteelPlant: "Edelstahlwerk",
    CircuitFoundry: "Schaltkreisfabrik",
    IntegratedCircuit: "integrierter Schaltkreis",
    OilWell: "Ölplattform",
    Wood: "Holz",
    LoggingCamp: "Forstbetrieb",
    LumberMill: "Sägewerk",
    Lumber: "Nutzholz",
    Paper: "Papier",
    PaperMill: "Papierfabrik",
    Book: "Buch",
    BookPublisher: "Buchverlag",
    OilRefinery: "Ölraffinerie",
    Sell: "Verkaufen",
    Upgrade: "Verbessern",
    Build: "Bauen",
    Buildings: "Gebäude",
    Iron: "Eisen",
    FuelType: "Wähle einen Kraftstoff",
    FuelCost: "Kraftstoffkosten",
    FuelEconomy: "Kraftstoffverbrauch",
    FuelInStorage: "%{fuel} im Lager",
    Plastic: "Kunststoff",
    Petrol: "Benzin",
    Buy: "Kaufen",
    Multiplier: "Multiplikator",
    MultiplierDesc: "Alle 10 Stufen erhältst du +1 Multiplikator",
    SellBuilding: "Gebäude verkaufen",
    PowerGrid: "Stromversorgung",
    SortBy: "sortieren nach",
    SortByPrice: "Wert",
    SortByAmount: "Menge",
    NotEnoughResources: "Unzureichende Ressourcen für diese Aktion",
    Transportation: "Transport",
    Cash: "Geld",
    Aluminum: "Aluminium",
    ResearchPoint: "Forschungspunkte",
    Unlock: "freischalten",
    BuildingUnlocked: "%{building} wurde freigeschalten",
    Science: "Wissenschaftspunkte",
    ScienceFromPowerDesc: "Stormerzeuger produzieren neben Strom auch eine kleine Menge Wissenschaftspunkte",
    Culture: "Kultur",
    School: "Schule",
    University: "Universität",
    Polytechnic: "Fachhochschule",
    Colosseum: "Kolosseum",
    WindTurbine: "Windkraftanlage",
    Engine: "Motor",
    EngineFactory: "Motorenhersteller",
    CameraFactory: "Kamerahersteller",
    Camera: "Kamera",
    Gun: "Waffe",
    GunFactory: "Waffenfabrik",
    Aircraft: "Flugzeug",
    AircraftFactory: "Flugzeugwerk",
    Zeppelin: "Zeppelin",
    ZeppelinFactory: "Zeppelinwerk",
    Tank: "Panzer",
    TankFactory: "Panzerwerk",
    CoalPowerPlant: "Kohlekraftwerk",
    PetrolPowerPlant: "Ölkraftwerk",
    Copper: "Kupfer",
    Gas: "Erdgas",
    GasPump: "Erdgasförderwerk",
    GasPowerPlant: "Gaskraftwerk",
    Missile: "Fernlenkgeschoss",
    MissileFactory: "Fernlenkgeschossmanufaktur",
    Rocket: "Rakete",
    RocketFactory: "Raketenfabrik",
    BuildingPermit: "Baugenehmigung",
    BuildingPermitDesc:
        "Du hast Baugenehmigungen für %{amount} Gebäude, davon hast du bereits %{amountBuilt} genutzt und %{amountLeft} übrig",
    BuildingLocked: "Das Gebäude ist noch nicht verfügbar, du musst es zuerst im Forschungslabor freischalten",
    MaxBuilders: "Max. Bauleiter",
    MaxBuildersDesc: "Anzahl der Gebäude, die du gleichzeitig bauen kannst",
    Silicon: "Silizium",
    AluminumMine: "Aluminiummine",
    CopperMine: "Kupfermine",
    SiliconMine: "Siliziummine",
    IronMine: "Eisenmine",
    CoalMine: "Kohlemine",
    Headquarter: "Hauptquartier",
    ResearchLab: "Forschungslabor",
    TradeCenter: "Handelszentrum",
    Resources: "Ressourcen",
    NotEnoughCash: "Du hast nicht genug Geld für diese Aktion",
    NotEnoughSwissMoney: "Du hast nicht genug Schweizer Franken für diese Aktion",
    BuildingNotEnoughFuel: "💡 Nicht genug %{fuel}",
    AutoSell: "automatischer Verkauf",
    Change: "ändern",
    StatisticsBureau: "Statistikbüro",
    LogisticsDepartment: "Logistikinstitut",
    From: "Von",
    Top20FuelCost: "Top 20 Kraftstoffverbraucher",
    To: "zu",
    TransportTime: "Transportdauer",
    Warehouse: "Lagerhaus",
    TradeWarehouse: "Handelslager",
    Coal: "Kohle",
    Video: "Video",
    ClothingFactory: "Bekleidungshersteller",
    Clothes: "Kleidung",
    Fashion: "Mode",
    FashionFactory: "Modedesigner",
    VideoFarm: "Videoproduzent",
    SantaFactory: "Weihnachtsmannfabrik",
    Santa: "Santa",
    Car: "Auto",
    CarFactory: "Automobilhersteller",
    Ship: "Schiff",
    SolarPanel: "Solarmodul",
    SolarPanelDesc: "💡 Solarmodule arbeiten nur 5 von 10 Sekunden - alle Kreisläufe sind miteinander verbunden",
    WindTurbineDesc:
        "💡 Windkraftanlagen arbeiten nur 8 von 10 Sekunden - Die Stromkreisläufe sind nicht miteinander verbunden",
    Movie: "Film",
    MovieStudio: "Filmstudio",
    Sitcom: "Sitcom",
    TVStudio: "TV-Studio",
    PC: "PC",
    GameStudio: "Spieleentwickler",
    Game: "Computerspiel",
    ComputerFactory: "Computerhersteller",
    Shipyard: "Werft",
    PowerUsage: "Energieverbrauch",
    PowerSupply: "Energieerzeugung",
    Level: "Stufe",
    Power: "Energie",
    CentralBank: "Zentralbank",
    ResourceInput: "Eingang",
    ResourceOutput: "Ausgang",
    ResourceStorage: "Lager",
    ResourceChange: "Wechsel",
    ResourceInOutDesc:
        "💡 Klicke oben auf Ein- oder Ausgang, um die entsprechenden Ein- und Ausgangsgebäude zu markieren",
    MarketUpdateIn: "Marktpreisaktualisierung in %{time}",
    Semiconductor: "Halbleiter",
    SemiconductorFactory: "Halbleiterwerk",
    Steel: "Stahl",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoinfarm",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoinfarm",
    Guitar: "Gitarre",
    GuitarFactory: "Gitarrenbauer",
    Drum: "Schlagzeug",
    DrumFactory: "Schlagzeugbauer",
    RecordingStudio: "Tonstudio",
    OperaHouse: "Opernhaus",
    CoalGasificationPlant: "Kohlevergasungsanlage",
    GasProcessingPlant: "Gasveredelungsanlage",
    Music: "Musik",
    Glass: "Glas",
    PhoneFactory: "Smartphonehersteller",
    Phone: "Smartphone",
    GlassFactory: "Glasmanufaktur",
    Oil: "Öl",
    Chromium: "Chrom",
    ChromiumMine: "Chrommine",
    Uranium: "Uran",
    EnrichedUranium: "angereichertes Uran",
    NuclearPowerPlant: "Kernkraftwerk",
    UraniumEnrichmentPlant: "Urananreicherungsanlage",
    UraniumMine: "Uranmine",
    Titanium: "Titan",
    TitaniumMine: "Titanmine",
    TitaniumAlloyPlant: "Titanmanufaktur",
    ChromiumAlloyPlant: "Chrommanufaktur",
    Input: "Eingang",
    PanelPosition: "Fensterposition",
    Output: "Produktion",
    OutputCapacity: "produzierte Ware",
    ResourceDeposit: "Ressourcen Absatz",
    AdjacentBonus: "Angrenzungsbonus",
    AdjacentBonusDesc:
        "Du erhältst %{bonus}% zusätzliche Kapazität für jedes angrenzende und arbeitende Gebäude derselben Art",
    ConsiderIncreaseProduction: "💡 Versuche die Produktion von %{resource} zu erhöhen.",
    ProductionCycleLength: "Produktionszyklus",
    ProductionCycleLengthDesc:
        "Dauer eines Produktionszyklus in Sekunden. Eine Verlängerung des Zyklus erhöht entsprechend die benötigen und hergestellten Ressourcen",
    MaxInputDistance: "Max. Importentfernung",
    MaxInputDistanceDesc:
        "Die maximale Distanz zu einem Gebäude, aus dem Rohstoffe bezogen werden, gemessen an der Zellenanzahl",
    AutoSellConcurrency: "automatische Verkaufsanzahl",
    AutoSellConcurrencyDesc: "Maximale Anzahl der Ressourcen, die gleichzeitig automatisch verkauft werden können",
    MaxAutoSellConcurrencyReached:
        "Du hast die maximale automatische Verkaufsanzahl erreicht, schalte einen anderen Handel ab, um diesen zu aktivieren",
    WallStreet: "Wall Street",
    MarketCap: "Marktkapitalisierung",
    MarketCapDesc: "Gesamtkapital (d. h. Marktwert) deines Unternehmens",
    BuildingValuation: "Gebäudewert",
    BuildingValuationDesc: "Gesamtwert deiner Gebäude, inklusive Baugenehmigungen und Aufwertungen",
    ResourcesValuation: "Ressourcenwert",
    ResourcesValuationDesc: "Gesamtwert der Ressourcen in deinem Lager",
    Battery: "Batterie",
    BatteryFactory: "Batteriefabrik",
    RatingBuy: "Kaufen",
    RatingSell: "Verkaufen",
    SwissShop: "Schweizer Bank",
    RatingHold: "Durchschnittlich",
    RatingOutperform: "Überdurchschnittlich",
    RatingUnderperform: "Unterdurchschnittlich",
    StockRating: "Unternehmensbewertung",
    JetEngine: "Düsentriebwerk",
    Helicopter: "Helikopter",
    Lithium: "Lithium",
    LithiumMine: "Lithiummine",
    LiionBatteryFactory: "Lithium-Ionen-Akkufabrik",
    HelicopterFactory: "Helikopterfabrik",
    Satellite: "Satellit",
    ToyFactory: "Spielzeughersteller",
    Toy: "Spielzeug",
    SpaceStation: "Weltraumstation",
    SpaceStationFactory: "Weltraumstationsmanufaktur",
    OperatingSystem: "Betriebssystem",
    OperatingSystemCompany: "Betriebssystemhersteller",
    LinuxDistribution: "Linux Vertrieb",
    Internet: "Internet",
    WebBrowser: "Webbrowser",
    Console: "Konsole",
    ConsoleFactory: "Konsolenhersteller",
    Train: "Zug",
    TrainFactory: "Zugwerk",
    ShoeFactory: "Schuhmacher",
    Shoes: "Schuhe",
    ArtilleryFactory: "Artilleriefabrik",
    Artillery: "Artillerie",
    SubmarineFactory: "U-Bootwerft",
    Submarine: "U-Boot",
    Spaceship: "Raumschiff",
    RobotFactory: "Roboterfabrik",
    Robot: "Roboter",
    SpaceshipFactory: "Raumschiffsfabrik",
    SatelliteFactory: "Satellitenmanufaktur",
    JetEngineFactory: "Düsentriebwerksfabrik",
    StockRatingDesc:
        "Die Aktienwertung beruht auf Wall Street-Auswertungen, wirkt sich auf deine Marktobergrenze aus und aktualisiert sich zusammen mit dem Markt",
    OfflineEarning: "Offlineverdienst",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offlineerwerbszeit",
    OfflineEarningTimeDesc: "Du erhältst Offlineeinkommen bis zu diesem Schwellenwert",
    BuyPermit: "Kauferlaubis",
    Settings: "Einstellungen",
    Sound: "Soundeffekt",
    SoundDesc: "Aktiviere Soundeffekte wie Klick- oder Fehlersounds",
    MusicDesc: "Musik einschalten: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Symbole",
    MisplacedBuilding: "⛔ %{building} kann nicht auf diese Ressource gebaut werden",
    HighlightBuildings: "Gebäude hervorheben, die ...",
    HighlightTurnedOff: "... abgeschaltet sind",
    HighlightStockpileModeOn: "... den Vorratsmodus aktiviert haben",
    HighlightProductionCycleNotDefault: "... einen Produktionszyklus > 1 haben",
    HighlightMaxInputDistanceNotDefault: "... die maximale Eingangsentfernung < ∞ haben",
    HighlightNotMakingProfit: "... keinen Gewinn machen",
    NBuildingsAreHighlighted: "%{n} Gebäude wurden hervorgehoben",
    TurnOffProduction: "Stilllegen",
    TurnOffProductionDesc:
        "Stellt die Produktion des Gebäudes ein. Das Gebäude wird keine Ressourcen mehr transportieren und keinen Strom verbrauchen",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "unbegrenzt",
    Transport: "Transport",
    TileModifier: "Zellenmodifikator",
    ShowAllModifiers: "Alle Modifikatoren anzeigen",
    HideAllModifiers: "Alle Modifikatoren ausblenden",
    NumberOfBuildings: "Anzahl deiner Gebäude",
    ShowContent: "Inhalte anzeigen",
    HideContent: "Inhalte ausblenden",
    BuyExpansionPack: "Für %{price} kaufen",
    Cities: "Städte",
    InputStrategy: "Eingangsstrategie",
    InputStrategyClose: "Nah",
    InputStrategyCloseDesc: "Bevorzugt das nächstgelegene Lagerhaus mit genügend Ressourcen",
    InputStrategyFar: "Distanz",
    InputStrategyFarDesc: "Bevorzugt das am weitesten entfernte Lagerhaus, mit genügend Ressourcen",
    InputStrategyAmount: "Menge",
    InputStrategyAmountDesc:
        "Bevorzuget das Lagerhaus mit der größten Menge an Ressourcen, unabhängig von der Entfernung",
    FuelCostSave: "Kraftstoffkosten sparen",
    FuelCostSaveDescV2:
        "Lagerhäuser lagern einen bestimmten Prozentsatz an Treibstoff für den Transport von Ressourcen ein. Besonderheit: Je höher die Stufe, desto mehr lagern sie ein",
    SoftwareCompany: "Softwareentwickler",
    Software: "Software",
    ScreenFactory: "Bildschirmhersteller",
    Screen: "Bildschirm",
    JoinDiscord:
        "Besuche unseren Discordserver, um die neuesten Updates und Tipps zu verfolgen und an spannenden Diskussionen teilzunehmen!",
    ClaimOfflineEarning: "Offlineeinnahmen kassieren",
    OfflineTime: "Offlinezeit",
    Minutes: "%{time}min",
    MaxUpgrade: "Maximale Stufe",
    MaxUpgradeDesc: "Du hast die maximale Stufe erreicht",
    ClaimAmount: "Geld +%{amount}",
    EffectiveTime: "Effektive Zeit",
    EffectiveTimeDesc: "Deine effektive Offlineverdienstzeit ist begrenzt auf %{time}min.",
    BuildSearchPlaceholder: "Gebe ein Gebäude oder eine Ressource für die Suche ein",
    MineOverlayWarning: "%{building} wird vom Zellenmodifikator nicht beeinflusst",
    WholesaleCenter: "Großhandel",
    OrderFrom: "Bestellung von %{name}",
    ExpireIn: "läuft aus in",
    Reward: "Belohnung",
    PerSecond: "%{time}/s",
    PolicyPoint: "Richtlinienpunkte",
    PolicyPointDesc: "💡 Je mehr Richtlinien aktiv sind, desto höher sind die Kosten für jede Richtlinie",
    NextOrderIn: "Nächste Bestellung in",
    FillOrder: "Bestellung ausliefern",
    RejectOrder: "Auftrag ablehnen",
    WholesaleCenterLocked:
        "Du brauchst mindestens %{required} Ressource zum Freischalten des Großhandelszentrums. Du hast nur %{current} der benötigten Ressourcen",
    OrderFilled: "Die Bestellung von %{from} wurde erfolgreich ausgeliefert!",
    PolicyCenter: "Bundestag",
    NewOrder: "Eine neue Bestellung von %{from} ist im Großhandelszentrum eingegangen",
    Policies: "Richtlinien",
    PolicyNotEnoughTime: "Du hast nicht genügend Richtlinienpunkte für diese Richtlinie",
    WholesaleCenterOrderFasterDesc:
        "Das Großhandelszentrum erhält Bestellungen 2x schneller und die Bestellgröße ist 2x größer",
    PolicyOilWellPowerx2: "Verdopple Ölquelle",
    PolicyOilWellPowerx2Desc: "Ölquellen produzieren 2x Öl und verbrauchen 2x Strom",
    HalfTransportSpeed: "Eile mit Weile",
    HalfTransportSpeedDesc:
        "Die Transportgeschwindigkeit wird um 25% verlangsamt und die Kraftstoffkosten um 25% gesenkt.",
    RefineryMoreOil: "Mehr Kraftstoff, Mehr Probleme",
    RefineryMoreOilDesc: "Ölraffinerien produzieren 50% mehr Benzin und 50% weniger Kunststoff",
    RefineryMorePlastic: "Mehr Plastic Mehr Probleme",
    RefineryMorePlasticDesc: "Ölraffinerien produzieren 50% mehr Kunststoff und 50% weniger Benzin",
    FreeOilTransportDesc: "Der Öltransport kostet keinen Kraftstoff, aber Ölquellen verbrauchen 2x Strom",
    SuperSteelMill: "Prinz Eisenherz",
    SuperSteelMillDesc: "Stahlwerke verbrauchen 50% weniger Kohle, aber 25% mehr Eisen und Strom",
    AlSemiconductor: "Al Schaltkreis",
    AlSemiconductorDesc: "Schaltungsgießereien verwenden Aluminium anstelle von Kupfer",
    CostSaver: "Kosteneinsparung",
    CostSaverDesc:
        "Wenn der Input eines Gebäudes mehr kostet als der Ertrag, stellt sich die Produktion automatisch ein",
    CostSaverBuildingDesc:
        "Die Kosteneinsparungsrichtlinie ist aktiv. Die Produktion wird, basierend auf ihrer Rentabilität, automatisch ein- und ausgeschaltet",
    CostSaverBuildingWarning:
        "Die Kosteneinsparungsrichtlinie ist aktiv. Du kannst die Produktion nicht manuell ändern",
    GlassUseCoal: "Schwarzes Glas",
    GlassUseCoalDesc: "Glasfabriken verbrauchen 50% mehr Kohle und 50% weniger Silizium",
    AdjacentBonusOnlyOutput: "Angrenzungsbonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Der Angrenzungsbonus erfordert nicht mehr Input, verbraucht aber mehr Strom und ist nur zu 50% effektiv",
    IronMine2xOutput: "Schwermetall",
    IronMine2xOutputDesc: "Eisenminen produzieren 2x Eisen, aber der Eisentransport kostet 2x Kraftstoff",
    SolarPanelAlwaysWork: "Die Sonne geht niemals unter",
    SolarPanelAlwaysWorkDesc: "Solarzellen arbeiten 100% der Zeit, produzieren aber 60% weniger Strom",
    SteelScience: "Wissen durch Stahl",
    SteelScienceDesc: "Stahlwerke verbrauchen 2x Ressourcen und produzieren zusätzlich Wissenschaftspunkte",
    ShoppingSpree: "Einkaufsbummel",
    ShoppingSpreeDesc:
        "Wenn die Produktion einer Ressource nicht ausreicht, kaufst du den Mangelbetrag automatisch am Marktplatz (wenn die Ressource automatisch weiterverkauft wird, wird Sie ignoriert).",
    ShoppingSpreeTradeCenterDesc:
        "💡 Wenn die Einkaufsbummelrichtlinie aktiviert ist, kauft der Marktplatz automatisch Ressourcen, die knapp sind",
    ExtraPolicyPoints: "Politischer Lobbyist",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromlegierungsanlagen verwenden kein Lithium, sondern 2x Eisen",
    DoubleTileModifier: "Die Kraft der Natur",
    TileModifierOutputOnly: "Zellenmodifikator Plus",
    GasPlantPetrol: "Gasliquidator",
    GasPlantPetrolDesc: "Gaskraftwerke verwenden zusätzliches Gas zur Herstellung von Benzin",
    CoalPlantFuel: "Kohle Liquidator",
    CoalPlantFuelDesc: "Kohlekraftwerke verwenden zusätzliche Kohle zur Herstellung von Kraftstoff",
    Welcome: "Willkommen",
    SeeTutorialAgain: "Tutorial wiederholen",
    HelpTranslateTheGame: "Hilf uns das Spiel zu übersetzen",
    NextTutorial: "weiter",
    Tutorial1:
        "Industry Idle ist ein <em> Ressourcenmanagement </em> -Spiel, indem du Fabriken bauen🏭, Waren produzieren📦 und Geld verdienen💸 kannst.<br><br>Lass uns zuerst einige grundlegende Dinge durchgehen, um dir den Einstieg zu erleichtern - es dauert nicht lange, Ehrenwort.",
    Tutorial2:
        "Alle Gebäude benötigen Strom⚡, du hast ein <em>Windrad</em>, welches Strom erzeugt. Du kannst deine aktuelle Netzversorgung auf der linken Seite der oberen Leiste sehen.<br><br> Möglicherweise hast du schon bemerkt, dass Windkraftanlagen nur <em>80%</em> der Zeit arbeiten. Du kannst auch andere Kraftwerkstypen bauen, die dauerhaft Strom erzeugen.",
    Tutorial3:
        "Du hast viele <em> Ressourcenablagerungen </em> auf der Karte. Um Ressourcen zu gewinnen, musst du Minen <em> auf </em>dem entsprechenden Vorkommen errichten. <br> <br> Zum Beispiel hast du eine <em> Ölquelle🛢️ </em>, die <em > Öl </em> aus einem Ölvorkommen extrahiert. <br><br>  Ressourcenvorkommen sind unbegrenzt - Du musst dir also keine Sorgen machen, dass sie versiegen. Abgesehen von Minen können andere Gebäude auf jeder leeren Kachel gebaut werden.",
    Tutorial5:
        "Um Geld zu verdienen, kannst du deine Ressourcen über das Handelszentrum verkaufen. Aktiviere dazu einfach den <em> automatischen Verkauf </em> für diese Ressource. <br><br>  Du kannst Ressourcen auch auf dem Marktplatz kaufen. Denke daran, <em> wenn du eine Ressource kaufen willst, erhöht sich ihr Preis </em> und wenn du eine Ressource verkaufst, senkt sich ihr Preis. <br> <br> Der Markt ist <em> unbeständig </ em > und der Preis 📈 ändert sich regelmäßig.",
    Tutorial6:
        "Um neue Gebäude zu bauen, musst du diese zuerst im <em> Forschungslabor🧪 </em> freischalten. Das Forschungslabor wandelt auch Wissenschaft in Forschungspunkte um. <br> <br> Deine Windkraftanlage (und andere Kraftwerke) produzieren beim Betrieb eine kleine Menge Wissenschaft. Des weiteren könntest du eine Schule und andere spezielle Gebäude bauen, um die Wissenschaft später anzukurbeln. <br> <br> Jetzt hast du alle Grundlagen gelernt und kannst beginnen, deine eigene Wirtschaft aufzubauen! Hier hast du etwas <em> Geld💸 </em> und <em> Benzin </em>, um dir eine Starthilfe zu verschaffen.",
    WelcomePlay: "Spielen",
    WelcomePlayMuted: "Spiel (🔇Musik)",
    Chat: "Chat",
    RestoreFromBackup: "Speicherstand wiederherstellen",
    RestoreFromBackupFail:
        "Wiederherstellung aus der Steam Cloud fehlgeschlagen: Bist du sicher, dass dort ein Spielstand existiert?",
    RestoreFromBackupTitle: "Bist du sicher?",
    RestoreFromBackupDesc:
        "Normalerweise brauchst du keine Wiederherstellungen aus der Cloud-Sicherung durchzuführen, es sei denn, deine lokalen Dateien gehen verloren. Cloud-Backups sind etwas älter als deine lokalen Speicherstände",
    ChangeName: "Ändern",
    SaveName: "Speichern",
    NameValidationRule: "Dein Name sollte nur Buchstaben und Zahlen enthalten und zwischen 5 und 15 Zeichen lang sein",
    NameValidationRuleProfanity: "Dein Name sollte keine vulgäre Sprache enthalten",
    ChatMessageRateLimit: "Du kannst nur alle 10 Sekunden eine neue Chatnachricht senden",
    NameSaved: "Dein Name wurde erfolgreich geändert",
    NoMessages: "Keine neuen Nachrichten",
    Leaderboard: "Bestenliste",
    Name: "Name",
    Tips1: "Aktienbewertungen haben 5 Kriterien: Kaufen, Überdurchschnittlich, Halten, Unterdurchschnittlich und Verkaufen",
    Tips2: "Gebäude stellen den Transport von Ressourcen ein, wenn bereits genug für die Produktion vorhanden ist, es sei denn, du aktivierst den Vorratsmodus",
    Tips3: "Die Kraftstoffkosten für den Ressourcentransport werden durch die Entfernung und die Menge der Ressourcen bestimmt",
    Tips4: "Gebäude transportieren eine Ressource nur, wenn die auf der Karte gefundene Menge die Eingabekapazität überschreitet",
    Tips5: "Gebäude transportieren eine Ressource nur vom Großhandelszentrum, wenn der automatische Verkauf für diese Ressource deaktiviert ist",
    Tips6: "Du kannst die Kraftstoffkosten für eine Ressource im entsprechenden Abschnitt zur Eingangskapazität anzeigen",
    Tips7: "Wenn du eine Ressource kaufen möchtest, erhöht sich der Preis. Wenn du eine Ressource verkaufst, senkt sich ihr Preis",
    Tips8: "Du kannst Statistiken und Diagramme für die Menge jeder Ressource und ihre zeitliche Änderung im Statistikbüro in Echtzeit anzeigen lassen",
    Tips9: "Die für ein Gebäude benötigten Forschungspunkte werden durch den Marktpreis seiner Inputressourcen bestimmt",
    Tips10: "Unterschiedliche Ressourcen werden auf dem Markt unterschiedlich bewertet - sei immer auf Marktschwankungen vorbereitet",
    Tips11: "Es ist eine gute Idee immer deine Strom- und Kraftstoffversorgung zu überprüfen, bevor du deine Produktion erweiterst",
    FPS30: "Energiesparmodus",
    OfflineModeDesc:
        "Es kann keine Verbindung zum Server hergestellt werden: Es werden keine Offlineeinnahmen generiert. Bitte überprüfe deine Internetverbindung",
    OptOut: "Abmelden",
    OptIn: "Zurücksetzen und aktivieren",
    LeaderboardOptOut: "Leaderboarddeaktivierung",
    LeaderboardOptIn: "Bestenliste zurücksetzen und aktivieren",
    LeaderboardOptInDesc:
        "Deine Daten müssen zurückgesetzt werden, bevor du die Bestenliste wieder aktivieren kannst. Bist du sicher?",
    RewardAdsFailed: "Das Belohnungsvideo wurde nicht abgeschlossen",
    OfflineEarningDoubleSuccess: "Du hast dein Offlineeinkommen verdoppelt",
    FPS30Desc:
        "Wenn du den Energiesparmodus aktivierst, wird das Spiel mit 30 FPS anstelle von 60 FPS ausgeführt. Dadurch hält dein Akku länger",
    HighlightAll: '"%{type}"hervorheben',
    HighlightInput: "🔍 %{type} Verbraucher hervorheben",
    HighlightOutput: "🔍 %{type} Erzeuger hervorheben",
    RunOutIn: "Leer in %{time}",
    SwissBank: "Schweizer Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Wenn du in einer neuen Stadt beginnst, erhältst du %{money} 💵",
    RestorePurchases: "Einkäufe wiederherstellen",
    RestorePurchasesSuccess: "Deine Einkäufe wurden wiederhergestellt",
    RestorePurchasesFailed: "Deine Einkäufe wurden nicht wiederhergestellt",
    ExpansionPacks: "Erweiterungspakete",
    ExpansionPack1: "Erweiterungspaket 1",
    RequireExpansionPack1: "Erweiterungspaket 1",
    RequireExpansionPack1Desc: "Dies ist nur mit dem Erweiterungspaket 1 verfügbar",
    RequireAnyExpansionPack: "erfordert den Erwerb eines Erweiterungspaketes",
    RequireAnyExpansionPackDesc: "Für diese Funktion musst du mindestens eines der Erweiterungspakete besitzen",
    HideRewardAd: "Belohnungsanzeigen ausblenden",
    HideRewardAdDesc:
        "Alle In-Game-Anzeigen sind optionale Belohnungsanzeigen. Dadurch werden alle Belohnungsanzeigen vor dem Spiel ausgeblendet.",
    HideDiscordBanner: "Discordbanner ausblenden",
    HideDiscordBannerDesc: "Ausblenden des Discord- und Storefrontbanners im Hauptquartier",
    HideChat: "Chatnachrichten ausblenden",
    PurchaseFailed: "Der Kauf wurde nicht abgeschlossen",
    PurchaseSteamContinue: "Bitte schließe deinen Einkauf bei Steam ab",
    PurchaseSuccess: "Der Kauf wurde abgeschlossen, vielen Dank für deine Unterstützung",
    PrestigeCurrency: "Schweizer Franken 💵",
    RestartDesc:
        "💡 Würdest du gerne neu starten? Du kannst oben auf Starte in einer neuen Stadt tippen und deine aktuelle Stadt auswählen",
    PrestigeGoBack: "bleiben",
    ProductionMultiplier: "Produktionsmultiplikator",
    ProductionMultiplierDesc:
        "Steigerung der Produktionskapazität aller Gebäude (einschließlich Minen, Fabriken, Kraftwerke, Wissenschafts- und Kulturgebäude)",
    FuelCostDiscount: "Kraftstoffkostenrabatt",
    FuelCostDiscountDesc: "Gibt einen Rabatt auf die Kraftstoffkosten beim Transport von Ressourcen",
    BuildingPermitCostDivider: "Kostenteiler für Baugenehmigungen",
    BuildingPermitCostDividerDesc: "Teile die Baugenehmigungskosten durch diesen Teiler",
    ExtraAdjacentBonus: "Zusätzlicher Benachbarungsbonus",
    ExtraAdjacentBonusDesc: "Zusätzliche Bonuskapazität für jedes benachbarte Produktionsgebäude des gleichen Typs",
    PrestigeAlertTitle: "Bist du sicher?",
    PrestigeAlertContent:
        "Dein Unternehmen wird aufgelöst. Du erhältst %{amount} Schweizer Franken und wirst eine neue Firma in %{city} gründen",
    PrestigeCurrencyDesc:
        "Dies ist das Geld auf deinem geheimen Schweizer Bankkonto. Du kannst es mitnehmen, wenn du in einer neuen Stadt anfängst",
    Prestige: "Einzahlen",
    Cancel: "Abbrechen",
    SaveFileCorrupted: "Spielstand beschädigt",
    LoadGameError: "Spiel konnte nicht geladen werden",
    LoadGameErrorMessage: "Fehlermeldung: %{message}",
    LoadGameErrorDesc:
        "Bitte überprüfe deine Internetverbindung. Wenn das Problem weiterhin besteht, wende dich bitte an den Support",
    ExpansionPackIncompatible:
        "Du importierst einen Spielstand mit Erweiterungspaketen, aber dein Spiel verfügt nicht über die erforderlichen Erweiterungspakete",
    CashIn: "Einzahlen",
    CurrentCity: "Aktuelle Stadt",
    CashInDesc:
        "Du erhältst diesen Betrag auf dein Schweizer Bankkonto, wenn du in einer neuen Stadt beginnst. Er basiert auf dem Marktwert deines Unternehmens und muss %{amount} erreichen, bevor du Schweizer Franken verdienen kannst",
    CitySize: "Kartengröße",
    GridType: "Zellentyp",
    StartInThisCity: "Starte in %{city}",
    CityBonus: "Stadtbonus",
    ResourceTilePercentage: "Ressourcenkacheln",
    MapSquareGrid: "quadratisch",
    MapHexGrid: "sechseckig",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li> Zeppelinfabriken sind freigeschaltet </li> <li> Halbleiterfabriken haben 2x Produktivität </li> <li> Werften haben 2x Kapazität </li> <li> Automobilhersteller haben 2x Kapazität </li> <li> Li-Ionen-Akkufabriken sind freigeschaltet </li> ",
    Toulouse: "Toulouse",
    Rome: "Rom",
    RomeBonus:
        "<li> Kolossen sind freigeschaltet </li> <li> Kolossen haben 2x Produktivität </li> <li> Beginne mit dem Policy Center auf Stufe 5 </li> <li> Opernhäuser haben 2x Kapazität </li> <li> Tonstudios produzieren auch Kultur </li> ",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li> Starte mit dem Forschungslabor auf Stufe 5 </li> <li> Fachhochschulen sind freigeschaltet </li> <li> Fachhochschulen haben 2x Kapazität </li> <li> Schulen haben 2x Kapazität </li> <li> Universitäten haben 2x Produktivität </li> ",
    HideNotProducing: "Ressourcen ausblenden, die nicht produziert werden",
    SortByStorage: "Lager",
    SortByName: "Name",
    PlayerTrade: "Spielerhandel",
    AddTradeFail: "Fehler beim Hinzufügen deines Handels",
    AddTradeExceedMaximumTrade:
        "Du kannst maximal %{number} aktive Handel haben, bitte beende zuerst einen anderen, oder brechen einen ab.",
    AddTradeSuccess: "Dein Handel wurde erfolgreich hinzugefügt",
    ClaimTradeFail: "Wenn du diesen Handel nicht beanspruchen kannst, versuche es später erneut",
    CancelTradeSuccess: "Dein Handel wurde erfolgreich abgebrochen",
    CancelTradeFail: "Dieser Handel konnte nicht abgebrochen werden. Bitte versuche es später erneut",
    AcceptTradeFail: "Dieser Handel wurde nicht akzeptiert. Bitte versuche es später erneut",
    PlayerTradeBanner: "Handel Ressourcen mit anderen Spielern",
    PlayerTradeResource: "Ressource",
    PlayerTradeAmount: "Menge",
    PlayerTradePrice: "Preis $",
    PlayerTradeValue: "Wert $",
    PlayerTradeWaiting: "Warten...",
    AddTrade: "Handel hinzufügen",
    AcceptTrade: "akzeptieren",
    CancelTrade: "abbrechen",
    ClaimTrade: "beanspruchen",
    FailedToImportSave: "Fehler beim Importieren der Sicherungsdateien",
    CancelActiveTradeFirst: "Du hast aktive Spielerhandel, bitte storniere / beanspruche diese zuerst",
    PlayerTradeValidRange: "Spanne: %{min} ~ %{max}",
    PlayerTradeUnavailable:
        "Du brauchst mindestens eine Ressource in Produktion oder im Lager um mit anderen Spielern zu handeln",
    PlayerTradeToClaim: "Du hast %{num} neue Handel zum Abholen auf dem Spielermarkt",
    PowerBank: "Stromspeicher",
    PowerBankBuildDesc: "Speichere überschüssigen Strom und sorge so auch für Stromversorgung bei Engpässen",
    WarehouseBuildDesc: "Transportiere und lagere alle Ressourcen mit geringeren Kraftstoffkosten",
    PowerBankChargeSpeed: "Ladegeschwindigkeit",
    PowerBankPowerLeft: "Strom übrig",
    PowerBankMoreCapacity: "Batteriesparmodus",
    PowerBankMoreCapacityDesc: "Stromspeicher laden 50% langsamer auf, haben aber 50% mehr Kapazität",
    PowerBankNotWorking: "⛔ Stromspeicher arbeiten nur neben einem Kraftwerk",
    ColorTheme: "Spielfarbthema",
    ColorThemeDesc: "Farbthema für Spielsymbole, Markierungen, Gitter und Hintergrund. ERFORDERT EINEN NEUSTART",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Siliziumminem produzieren 2x Silizium, aber benötigen 50% mehr Strom und die Transportkosten für Silizium sind 50% höher.",
    CoalMine2xOutput: "Industrielle Revolution",
    CoalMine2xOutputDesc:
        "Kohleminen produzieren 2x soviel Kohle, aber benötigen 50% mehr Strom und die Transportkosten für Kohle sind um 50% erhöht.",
    AlMine2xOutput: "Aluminumschmelze",
    AlMine2xOutputDesc: "Aluminumminen produzieren 2x so viel Aluminium und verbrauchen 2x so viel Strom.",
    LoggingCamp2xOutput: "Abholzung",
    LoggingCamp2xOutputDesc: "Forstbetriebe produzieren 2x so viel Holz und die Transportkosten werden verdoppelt.",
    PowerBankLeft: "Energiespeicher",
    ColorThemeEditor: "Farbschemen bearbeiten",
    ColorThemeEditorDesc: "Du kannst im aktuellen Schema Farben überschreiben. Du hast aktuell %{num} überschrieben.",
    ColorThemeEditorSave: "Speichern",
    ColorThemeEditorReset: "Zurücksetzen",
    ColorThemeEditorResetAll: "Alle zurücksetzen",
    NewMessageMentions: "Du wurdest in einer Nachricht erwähnt: %{message}",
    HideChatMentions: "Chaterwähnungen ausblenden",
    HideChatMentionsDesc: "Blende die Audio- und Popupbenachrichtigungen aus, wenn eine Chatnachricht mich erwähnt,",
    AcceptTradeFailRateLimit: "Du kannst nur alle %{time} Sekunden einen Handel akzeptieren",
    DowngradeBuilding: "Herabstufen",
    WarehouseAddInput: "Route hinzufügen",
    WarehouseTapToSelect: "Tippe zur Auswahl auf die Karte...",
    WarehouseFindOnMap: "🔍 auf der Karte finden",
    WarehouseRemoveRoute: "entfernen",
    WarehouseAddRouteFail: "Route konnte nicht hinzugefügt werden: Die ausgewählte Kachel ist keine gültige Quelle",
    LevelN: "Level %{level}",
    Surplus: "Überschuss",
    Production: "Produktion",
    Consumption: "Verbrauch",
    WarehouseInputCapacityDescV2: "Gesamtkapazität des Eingangsstransports, gleichmäßig auf alle Strecken verteilt",
    PlayerCountryFlag: "Spielerflagge",
    PlayerCountryChooseFlag: "In alphabetischer Reihenfolge des Länderkürzels",
    WindTurbineAlwaysWork: "Der Wind wird stärker",
    WindTurbineAlwaysWorkDesc: "Windkraftanlagen arbeiten 100% der Zeit, produzieren aber 30% weniger Strom",
    BookPublisherScience: "Wissenschaftsliteratur",
    BookPublisherScienceDesc: "Buchverläge produzieren Wissenschaft statt Kultur",
    BatteryFuelEconomy: "Wiederaufladbare Batterie",
    BatteryFuelEconomyDesc:
        "Der Kraftstoffverbrauch der Batterie verbessert sich um 100% (daher 50% Kraftstoffkosten).",
    ShowTheoreticalInputOutputCapacity: "Zeigt die theoretische Ein- und Ausgabekapazität an",
    SpecialTransportCost: "Ressourcen mit besonderen Transportkosten",
    FreeTransportCost: "Ressourcen mit kostenlosem Transport",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Ressourcen erscheinen in der Regel in Gruppen.</li> <li>Das Lagerhaus bietet 50% mehr Kraftstoffeinsparung.</li> <li>Einzigartiges Gebäude: Manga-Verlag</li> <li>Einzigartiges Gebäude: Anime-Studio</ li ><li>Halbleiterchipfabriken haben 2x Produktivität</li> <li>Li-Ionen-Batteriefabriken haben 2x Kapazität</li> <li>Batteriefabriken sind entsperrt</li> <li>Batteriefabriken haben 2x Kapazität</ li > <li>Der Kraftstoffverbrauch der Batterie erhöht sich um 100%.</li> <li>Batteriefabriken benötigen keine Kohle.</li> <li>Beginnen Sie mit 100K-Batterien</li>",
    HideChatDescV2:
        "Chatnachricht in der unteren Symbolleiste ausblenden. Durch das Anzeigen von Chatnachrichten stimmst du den ",
    HideChatDescV2ToS: "Nutzungsbedingungen zu",
    IntegratedCircuitFab: "Fabrik für integrierte Schaltkreise",
    MangaPublisher: "Mangaverlag",
    Manga: "Manga",
    AnimeStudio: "Animestudio",
    Anime: "Anime",
    PlayerTradeAction: "Auktion",
    PlayerTradeBuy: "Kaufen",
    PlayerTradeSell: "Verkaufen",
    PlayerTradeBid: "Verkauf",
    PlayerTradeAsk: "Ankauf",
    ClaimTradeSuccessV2: "Dein Handel wurde erfolgreich angenommen: %{cashOrResource}",
    AcceptTradeSuccessV2: "Dieser Handel wurde von dir abgeschlossen: %{cashOrResource}",
    ResourceExplorer: "Ressourcenentdecker",
    ResourceExplorerDesc: "Ermöglicht das Extrahieren von Ressourcen aus einer leeren Kartenkachel",
    ResourceExplorerDescLong:
        "💡 Ressourcenentdecker haben keinen Benachbarungsbonus. Der Stromverbrauch ist je nach Ressource unterschiedlich",
    ResourceExplorerSelectResource: "Erkunden",
    ProductionSettings: "Produktionseinstellungen",
    PlayerTradePartialFillTitle: "Wähle Füllprozentsatz",
    PlayerTradeAmountNotValidV2: "Der minimal zulässige Handelsbetrag beträgt 1",
    PlayerTradeOptOut: "Du hast dich von der Bestenliste abgemeldet und kannst nicht mit anderen Spielern handeln",
    FirstTimeReadGuide:
        "💡 Benötigst du ein bisschen Hilfe beim Spielen? Tippe hier, um den Anfängerleitfaden zu lesen!",
    ReadSteamGuideV2: "Spielanleitungen",
    ReadSteamGuideV2Desc:
        "Du kannst von der Community erstellte Anleitungen auf Steam lesen - oder deine eigenen erstellen",
    ChatMessageTooLong: "Deine Chatnachricht hat die maximal zulässigen Zeichen überschritten",
    ChatPlaceholderV2: "Gebe deine Nachricht ein: max %{length} Buchstaben",
    ProfitBreakdownOutput: "%{res} Erzeugung",
    ProfitBreakdownInput: "%{res} Verbrauch",
    ProfitBreakdownFuel: "Kraftstoffkosten",
    BuildingProfit: "Gewinn",
    RestoreBackup: "Wiederherstellen",
    SteamLogin: "Melde dich mit Steam an",
    SteamLoginDialogDesc:
        "Für deinen lokalen Speicherstand ist ein Erweiterungspaket aktiviert. Du musst dich über Steam anmelden, um fortzufahren oder deine lokalen Daten löschen und von vorne beginnen",
    SteamLoginDesc:
        "Wenn du Erweiterungspakete bei Steam besitzen, kannst du nach der Anmeldung mit Erweiterungspaketen online spielen",
    SteamLoginYes: "Anmelden",
    SteamLoginNo: "Löschen & von vorne beginnen",
    KungFuDojo: "Kung-Fu Dojo",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojo",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Internationaler Exporthandel",
    FreeTransportToTradeCenterDesc:
        "Der Transport zum Handelszentrum kostet keinen Kraftstoff, aber der Transport vom Handelszentrum kostet 50% mehr Kraftstoff",
    TaiChi10xCulture: "Perle des Orients",
    PlayerTradeYouHave: "Auf Lager: %{amount}",
    FiberFactory: "Glasfaserfabrik",
    Fiber: "Glasfaser",
    Achievements: "Errungenschaften",
    AchievementsDesc: "Du hast %{number} von %{total} Errungenschaften erreicht",
    AchievementsReward: "Belohnung: Schweizer Franken +%{swiss}",
    AchievementsRewardToast: "Du hast die Belohnung beansprucht:  Schweizer Franken +%{swiss}",
    AchievementsClaim: "Einsammeln",
    AchievementsToast: "Du hast %{name} erreicht, fordere deine Belohnung im Hauptquartier an",
    AchievementStockholm100: "Freshman Viking",
    AchievementStockholm100Desc: "Verdiene 100 Schweizer Franken in Stockholm in einem einzigen Druchlauf",
    AchievementStockholm500: "Graduate Viking",
    AchievementStockholm500Desc: "Verdiene 500 Schweizer Franken in Stockholm in einem einzigen Druchlauf",
    AchievementStockholm1000: "Experienced Viking",
    AchievementStockholm1000Desc: "Verdiene 1000 Schweizer Franken in Stockholm in einem einzigen Druchlauf",
    AchievementOslo100: "Norwegian Oil Hobbyist",
    AchievementOslo100Desc: "Verdiene 100 Schweizer Franken in Oslo in einem einzigen Druchlauf",
    AchievementOslo500: "Norwegian Oil Enthusiast",
    AchievementOslo500Desc: "Verdiene 500 Schweizer Franken in Oslo in einem einzigen Druchlauf",
    AchievementOslo1000: "Norwegian Oil Tycoon",
    AchievementOslo1000Desc: "Verdiene 1000 Schweizer Franken in Oslo in einem einzigen Druchlauf",
    AchievementRotterdam100: "Pinwheel Owner",
    AchievementRotterdam100Desc: "Verdiene 100 Schweizer Franken in Rotterdam in einem einzigen Druchlauf",
    AchievementRotterdam500: "Wind Mill Owner",
    AchievementRotterdam500Desc: "Verdiene 500 Schweizer Franken in Rotterdam in einem einzigen Druchlauf",
    AchievementRotterdam1000: "Wind Turbine Owner",
    AchievementRotterdam1000Desc: "Verdiene 1000 Schweizer Franken in Rotterdam in einem einzigen Druchlauf",
    AchievementDetroit100: "Local Car Dealer",
    AchievementDetroit100Desc: "Verdiene 100 Schweizer Franken in Detroit in einem einzigen Druchlauf",
    AchievementDetroit500: "Regional Car Distributor",
    AchievementDetroit500Desc: "Verdiene 500 Schweizer Franken in Detroit in einem einzigen Druchlauf",
    AchievementDetroit1000: "National Car Monopoly",
    AchievementDetroit1000Desc: "Verdiene 1000 Schweizer Franken in Detroit in einem einzigen Druchlauf",
    AchievementBoston100: "Bachelor of Earning Money",
    AchievementBoston100Desc: "Verdiene 100 Schweizer Franken in Boston in einem einzigen Druchlauf",
    AchievementBoston500: "Master of Gaining Money",
    AchievementBoston500Desc: "Verdiene 500 Schweizer Franken in Boston in einem einzigen Druchlauf",
    AchievementBoston1000: "Ph.D in Printing Money",
    AchievementBoston1000Desc: "Verdiene 1000 Schweizer Franken in Boston in einem einzigen Druchlauf",
    AchievementRome100: "Diocletian",
    AchievementRome100Desc: "Verdiene 100 Schweizer Franken in Rom in einem einzigen Druchlauf",
    AchievementRome500: "Constantine the Great",
    AchievementRome500Desc: "Verdiene 500 Schweizer Franken in Rom in einem einzigen Druchlauf",
    AchievementRome1000: "Caesar Augustus",
    AchievementRome1000Desc: "Verdiene 1000 Schweizer Franken in Rom in einem einzigen Druchlauf",
    AchievementHamburg100: "Deutschland",
    AchievementHamburg100Desc: "Verdiene 100 Schweizer Franken in Hamburg in einem einzigen Druchlauf",
    AchievementHamburg500: "Vaterland",
    AchievementHamburg500Desc: "Verdiene 500 Schweizer Franken in Hamburg in einem einzigen Druchlauf",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Verdiene 1000 Schweizer Franken in Hamburg in einem einzigen Druchlauf",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Verdiene 100 Schweizer Franken in Toulouse in einem einzigen Druchlauf",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Verdiene 500 Schweizer Franken in Toulouse in einem einzigen Druchlauf",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Verdiene 1000 Schweizer Franken in Toulouse in einem einzigen Druchlauf",
    AchievementHongKong100: "Hobbyist Trader",
    AchievementHongKong100Desc: "Verdiene 100 Schweizer Franken in Hong Kong in einem einzigen Druchlauf",
    AchievementHongKong500: "Professional Broker",
    AchievementHongKong500Desc: "Verdiene 500 Schweizer Franken in Hong Kong in einem einzigen Druchlauf",
    AchievementHongKong1000: "Hedge Fund Manager",
    AchievementHongKong1000Desc: "Verdiene 1000 Schweizer Franken in Hong Kong in einem einzigen Druchlauf",
    AchievementStPetersburg100: "The Grand Duke",
    AchievementStPetersburg100Desc: "Verdiene 100 Schweizer Franken in St. Petersburg in einem einzigen Druchlauf",
    AchievementStPetersburg500: "The Tsesarevich",
    AchievementStPetersburg500Desc: "Verdiene 500 Schweizer Franken in St. Petersburg in einem einzigen Druchlauf",
    AchievementStPetersburg1000: "The Tsar of All Russia",
    AchievementStPetersburg1000Desc: "Verdiene 1000 Schweizer Franken in St. Petersburg in einem einzigen Druchlauf",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Verdiene 100 Schweizer Franken in Osaka in einem einzigen Druchlauf",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Verdiene 500 Schweizer Franken in Osaka in einem einzigen Druchlauf",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Verdiene 1000 Schweizer Franken in Osaka in einem einzigen Druchlauf",
    SteamAutoCloudBackup: "Steam Cloud Auto Sicherung",
    SteamAutoCloudBackupFailed: "Steam Cloud Auto Backup fehlgeschlagen: %{error}",
    SteamManualBackup: "Manuelles Steam Backup erzwingen",
    UILoading: "Lädt...",
    BuildingResourceBreakdown: "Aufschlüsselung des Leerlaufbetrags",
    SortByDeficit: "Defizit",
    SortByRunOut: "Läuft aus",
    SocialNetworkInc: "Social Network Inc.",
    SocialNetwork: "Social Network",
    DatabaseCompany: "Datenbankunternehmen",
    Database: "Datenbank",
    SatelinkInc: "Satelink Inc",
    GameStationInc: "GameStation Inc",
    AirShuttleInc: "Air Shuttle Inc",
    AircraftCarrierFactory: "Flugzeugträgerfabrik",
    AircraftCarrier: "Flugzeugträger",
    MapExclusive: "Karten exklusiv",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Automobilhersteller verwenden Batterien anstelle von Benzin und benötigen nur 50% der Menge",
    HongKongBonusV2:
        "<li>Einzigartiger Marktpreisalgorithmus - Preise und Aktienbewertung folgen der Normalverteilung (Glockenkurve)</li><li>Marktpreisaktualisierungen und das Zurücksetzen von Handelsquoten sind doppelt so häufig (jede Stunde)</li><li>Forschung kann über gehandelte Ressourcen freigeschaltet werden</li><li>Einzigartiges Gebäude: Kung-Fu Dojo</li><li>Einzigartiges Gebäude: Tai-Chi Dojo</li><li>Erhöhung der maximal zulässigen Anzahl aktiver Spieler-Trades um 50%</li><li>Beginne mit 1 weiteren Auto-Sell-Parallelität</li><li>Einzigartige Richtlinie: Internationaler Exporthandel</li><li>Einzigartige Richtlinie: Perle des Orients</li><li>Das Großhandelszentrum benötigt zum Freischalten nur 4 Ressourcen</li><li>Beginne mit 100 Millionen Bargeld</li>",
    TaiChi10xCultureDescV2:
        "Kostenloser Transport von Kung-Fu und Tai-Chi. Filmstudios haben doppelte Kapazität, verbrauchen aber 50% mehr Strom",
    SettingsFullScreen: "Vollbild",
    SettingsFullScreenDesc: "Führe das Spiel im Vollbildmodus aus. Nur für die Steamversion verfügbar",
    LeaderboardByAllPrestigeCurrency: "Summe verdienter Schweizer Franken",
    LeaderboardByCash: "Aktueller Kontostand",
    LeaderboardTotalValuation: "Gesamtwert",
    LeaderboardDescV2: "Sieh dir an, wo die Top-Spieler sind",
    LastUpdatedAt: "Zuletzt aktualisiert um",
    DetroitBonusV3:
        "<li>Motorenhersteller sind entsperrt</li><li>Motorenhersteller haben 2x Produktivität</li><li>Automobilhersteller haben 2x Kapazität</li><li>Automobilhersteller verwenden Gas anstelle von Benzin</li><li>Kostenloser Autotransport</li><li>Nikola Tesla Richtlinie ist kostenlos</li><li>Zugwerke haben 2x Kapazität</li>",
    SaveAndExit: "Spiel speichern und beenden",
    SaveAndExitDesc:
        "Spiel speichern und beenden. Dies ist nur in der Steamversion verfügbar und entspricht der Schaltfläche zum Schließen in der Fensterleiste",
    AutoSellResourceWarningShortLabel: "💡Automatischer Verkauf",
    AutoSellResourceWarningDesc:
        "Du verkaufst diese Ressource automatisch. Der im Handelszentrum verfügbare Betrag kann hier nicht verwendet werden",
    PlayerTradeLocalPrice: "Lokaler Preis: %{price}",
    ChatForceScroll: "Scrollen erzwingen",
    ChatForceScrollDesc:
        "Wenn Scrollen erzwingen aktiviert ist, wird der Chat immer dann gescrollt, wenn eine neue Nachricht eingeht. Andernfalls wird nur gescrollt, wenn du dich bereits unten befindest",
    ResourceExplorer2: "Ressourcenfinder 2.0",
    ConstructionCancel: "Bau abbrechen",
    PolicyBlueprint: "Blauplan",
    PolicyBlueprintDesc:
        "Der Bau eines Gebäudes beginnt nicht automatisch - er muss manuell gestartet werden (KOSTENLOSE RICHTLINIE)",
    HighlightUnderConstruction: "... , deren Bau nicht fertig gestellt wurde.",
    HighlightUnderLevel10: "... , die unter Stufe 10 sind.",
    HighlightUnderLevel20: "... , die unter Stufe 20 sind.",
    HighlightUnderLevel30: "... , die unter Stufe 30 sind.",
    Logout: "Du wurdest abgemeldet",
    ConstructionStatusQueueingV2: "Anstehend",
    ConstructionStatusPausedV2: "pausiert",
    ConstructionStatusBuildingV2: "Gebäude",
    ConstructionStatusUnpaidV2: "Unbezahlt",
    ConstructionStatus: "Baustatus",
    ConstructionStart: "Start",
    CostFree: "kostenlos",
    PlaceBlueprint: "Das Platzieren einer Gebäudeblaupause ist kostenlos",
    PlayerTradePriceNotValidV2: "Der Handelspreis muss zwischen %{min} und %{max} liegen",
    MarketNews: "Marktneuigkeiten",
    MarketNewsApplyToYou: "Nur für dich",
    MarketNewsApplyToGlobal: "Global",
    MarketNewsHighlightAffected: "🔍 hervorheben",
    MarketNewsFilterInput: "Alle %{res} Verbraucher",
    MarketNewsFilterOutput: "Alle %{res} Erzeuger",
    MarketNewsFilterBoth: "Alle %{res} Verbraucher und Erzeuger",
    MarketNewsIncrease: " erhöht um %{percent}",
    MarketNewsDecrease: " verringert um %{percent}",
    MarketNewsBuilding: "Dieses Gebäude wird von %{num} Neuigkeiten betroffen",
    StockholmBonusV2:
        "<li>Einzigartiges Gebäude: Musikproduzent</li><li>Forstbetriebe haben 2x Produktivität</li><li>Papierfabriken sind entsperrt</li><li>Schaltungsgießereien haben 2x Produktivität</li><li>Die 'Politik der Wissenschaft Richtlinie' ist kostenlos</li>",
    FreeOilTransportV2: "Elektronischer Öltransport",
    Tutorial4P1:
        "Der Transport von Ressourcen kostet Kraftstoff. Es gibt verschiedene Kraftstoffarten, momentan verwendest du <em>petrol⛽</em> als Kraftstoff. Du besitzt eine <em>Ölraffinerie</em>, welche das Öl auf der Ölquelle verbraucht und Benzin herstellt.<br><br>Die kleinen, sich bewegenden <em>Punkte</em> stellen den Transport der Ressourcen dar. Du solltest deine Gebäudestandorte optimieren, um die Distanz zu minimieren.<br><br>Das <em>Aufwerten</em> deiner Gebäude erhöht deren Produktion, aber erhöht ebenfalls deren Stromverbrauch, sowie die benötigten Ressourcen.",
    Tutorial4P2:
        "Du kannst deinen Kraftstofftypen im <em>Logistikinstitut🚦</em> ändern. Auf dieser Karte kannst du auch <em>Erdgas</em> als Kraftstoff verwenden.<br><br>Das Logistikinstitut zeigt auch deine Transportwege an, auf denen der meiste Kraftstoff verbraucht wird - Behalte es im Auge.<br><br>Denke daran, <em> sicherzustellen, dass deine Kraftstoffproduktion über dem Verbrauch liegt </em>, da sonst die Produktion stoppt, sobald der Kraftstoff ausgeht.<br><br>Mach dir in diesem Fall keine Sorgen, du kannst notfalls Kraftstoff im Handelszentrum oder bei anderen Spielern kaufen",
    Tutorial5P2:
        "<em>Die Statistikagentur📊</em> bietet einen guten Überblick deiner Produktionen. Du kannst eine detaillierte Aufschlüsselung deiner Ressourcenein- und -ausgänge einsehen.<br><br>Es gibt auch viele nützliche Diagramme📈 - Du solltest sie bei der Aufwertung deiner Produktion berücksichtigen.<br></br>Dein <em>Geld💰, Stromüberschuss⚡ und Kraftstoffüberschuss⛽</em> werden auch in der oberen linken Ecke angezeigt. Wenn eine davon rot wird, solltest du herausfinden, was los ist.",
    MusicProducer: "Musikproduzent",
    PlasticFiber: "Kunststofffaser",
    PlasticFiberDesc: "Glasfaserfabriken verwenden 50% mehr Kunststoff, aber 50% weniger Glas",
    SellRefundPercentage: "Rückerstattung verkaufen / herabstufen",
    SellRefundPercentageDesc:
        "Dies ist der Prozentsatz, den du beim Verkaufen oder Herabstufen eines Gebäudes an Geld und Ressourcen zurückerstattet bekommst.",
    SellBuildingDescV2:
        "Durch den Verkauf eines Gebäudes erhälst du %{percent} deiner Investitionen zurück und %{percent} der Ressourcen werden zum Handelszentrum zurücktransportiert",
    BuilderMoveSpeed: "Bauarbeiter Bewegungsgeschwindigkeit",
    BuilderMoveSpeedDesc: "Die Geschwindigkeit, mit der sich Bauarbeiter bewegen, um Gebäude zu bauen",
    EBookInc: "eBook Inc.",
    ResourceBooster: "Ressourcenverstärker",
    BuildWarningTitle: "Gebäude funktioniert möglicherweise nicht",
    BuildWarningTitleDesc: "%{reason}. Bist du sicher, dass du auf dieser Zelle bauen willst?",
    BuildWarningBuildAnyway: "Trotzdem bauen",
    ResourceBoosterNotWorking: "⛔ Ressourcenverstärker funktionieren nur in der Nähe von Lagerstätten",
    ResourceBoosterBuildings: "Gebäude werden verstärkt",
    BuildingResourceConversion: "%{resource} umgewandelt",
    AllTimeSwissMoneyEarned: "Gesamstmenge Schweizer Franken: %{number}",
    BuildingUpgradeCostDivider: "Kostenteiler für Gebäudeaufwertungen",
    AchievementSoftwareGiant: "Software Gigant",
    AchievementSoftwareGiantDesc:
        "Erstelle auf derselben Karte ein Softwareunternehmen der Stufe 10, ein Betriebssystemunternehmen der Stufe 10, ein Datenbankunternehmen der Stufe 10 und einen Webbrowser der Stufe 10",
    AchievementSpaceRace: "Weltraumrennen",
    AchievementSpaceRaceDesc:
        "Baue auf derselben Karte eine Raketenfabrik der Stufe 10, eine Satellitenfabrik der Stufe 10, eine Raumschifffabrik der Stufe 10 und eine Raumstationsfabrik der Stufe 10",
    AchievementToTheMoon: "Zum Mond",
    AchievementToTheMoonDesc:
        "Baue eine Bitcoinfarm der Stufe 40 und eine Dogecoinfarm der Stufe 40. Besitze 1B Bitcoin und 1B Dogecoin",
    ItsAllGreen: "Alles ist grün",
    ItsAllGreenDesc: "Betreibe 50 Produktionslinien ohne jegliches Produktionsdefizit",
    DeepInRed: "Tiefrot",
    DeepInRedDesc: "Haben Sie 50 Produktionslinien mit Produktionsdefiziten",
    UseScientificNotation: "Wissenschaftliche Zahlen verwenden",
    UseScientificNotationDesc:
        "Verwende die exponentielle Darstellung für Zahlen größer als 999,9T",
    LogoutDescV2:
        "Du hast dich auf einem anderen Gerät angemeldet, dieses Gerät wurde dadurch abgemeldet. Du kannst dich wieder anmelden, aber das andere Gerät wird abgemeldet. ",
    LogBackIn: "Anmelden",
    ServerDisconnected:
        "Die Verbindung zum Server wurde getrennt, überprüfe bitte deine Internetverbindung und starte das Spiel neu",
    BuildingUpgradeCostDividerDescV2: "Teile die Kosten für die Gebäudeaufwertungen durch diesen Teiler",
    ResourceBoosterDesc: "Steigert die Leistung benachbarter Minen",
    BlockUserChatTitle: "Blockiere %{user}",
    BlockUserChatAction: "Blockieren",
    BlockUserChatDesc:
        "Das Blockieren wird während dieser Spielsitzung aktiv bleiben und wird erst mit dem Neustart des Spiels rückgängig gemacht.",
    ChangeNameCooldown: "Du kannst deinen Namen nur ein Mal alle %{hour} ändern",
    AtomicBombFactory: "Atombombenlabor",
    AtomicBomb: "Atombombe",
    DynamiteFactory: "Sprengstofffabrik",
    Dynamite: "Sprengstoff",
    NuclearMissileFactory: "Atomraketenfabrik",
    NuclearMissile: "Atomrakete",
    LiquidPropellantFactory: "Fabrik für flüssigen Treibstoff",
    GasPropellantFactory: "Gas-Treibstofffabrik",
    Propellant: "Treibstoff",
    ProjectV2: "Projekt V-2",
    ICBMFactory: "Interkontinentalraketenfabrik",
    ICBM: "Interkontinentalraketen",
    RadarFactory: "Radarfabrik",
    Radar: "Radar",
    SpaceForceCommand: "Space Force Kommando",
    SpaceForce: "Space Force",
    SpaceColony: "Weltraumkolonie",
    SpaceColonyInc: "Weltraumkolonieagentur",
    ProjectVostok: "Projekt Wostok",
    AdjacentBonusSquare: "Angrenzendes Bonusfeld",
    AdjacentBonusSquareDesc:
        "Der angrenzende Bonus ist 50% effektiver, aber die Zellenmodifikatoren skalieren von -15% bis + 15%.",
    ResourceBoosterSquare: "Ressourcen-Verstärker Quadrat",
    ResourceBoosterSquareDesc:
        "Ressourcenverstärker sorgen für 25% mehr Boost, aber ihr Wissenschaftspunkte- und Stromverbrauch steigt um 25%",
    SteelMillx2: "Stahlofenmodernisierung",
    SteelMillx2Desc:
        "Stahlwerke und Edelstahlwerke haben doppelte Kapazität, verbrauchen jedoch die doppelte Menge Strom",
    FuelDynamite: "Kraftstoff Dynamit",
    FuelDynamiteDesc: "Dynamitfabriken verwenden Ihren aktuellen Kraftstoff anstelle von Öl",
    StPetersburgBonusV2:
        "<li>Uranminen haben 2x Produktion</li><li>Urananreicherungsanlagen haben doppelte Kapazität</li><li>Der Urantransport kostet 50% weniger Kraftstoff</li><li>Kostenloser Waffentransport</li><li>Das Projekt Wostok hat eine Kapazität von 2x</li>",
    ToulouseBonusV2:
        "<li>Titanminen haben 2x Prdouktion</li><li>Urananreicherungsanlagen haben eine doppelte Produktivität</li><li>Triebwerksfabriken haben eine Kapazität von 2x</li><li>Flugzeugfabriken haben 2x Produktivität</li><li>Raketenfabriken haben eine Kapazität von 2x</li>",
    BuildingPermitsNeededDesc: "Die fehlt die nötige Baugenehmigung, um das Gebäude hier zu bauen.",
    BuildingPermitsNeeded: "Baugenehmigungen erforderlich",
    BuyMissingPermits: "Fehlende Baugenehmigungen kaufen",
    GPUIsBusy: "Deine GPU ist überlastet",
    GPUIsBusyDesc:
        "Dein Betriebssystem hat die Grafik des Spiels angehalten, da die GPU mit anderen Aufgaben beschäftigt ist. Du kannst das Spiel neu laden, um fortzufahren. Wenn das nicht funktioniert, starte das Spiel neu",
    SaveAndReloadGame: "Spiel speichern und neu laden",
    ResearchLabCultureInput: "Die Renaissance",
    ResearchLabCultureInputDesc: "Das Forschungslabor hat doppelte Kapazität, verbraucht aber zusätzlich Kultur",
    GasPumpx2Output: "Hochdruck-Gaspumpe",
    GasPumpx2OutputDesc: "Erdgaspumpen haben 2x Produktivität, verbrauchen aber 2x Strom",
    LeaderboardValuationPerHour: "Gesamtwert pro Stunde",
    LeaderboardValuationPerHourPerSwiss: "Gesamtwert pro Stunde, pro Schweizer Franken",
    LeaderboardValuationPerHourNewPlayers: "Gesamtwert pro Stunde (< 1000 Schweizer Franken)",
    LeaderboardValuationPerBuilding: "Gesamtwert pro Gebäude",
    BuildingCustomColor: "Gebäudefarbe",
    BuildingCustomColorReset: "Zurücksetzen",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Pro 4 verschiedenen Gebäudetypen erhältst du 1 kostenlose Baugenehmigung</li><li>Einzigartige Richtlinie: Produktionsdiversifizierung</li><li>Einzigartiges Gebäude: Ahornsirupfabrik</li><li>Kostenloser Ahornsiruptransport</li><li>Einzigartiger Kraftstoff: Ahornsirup</li><li>2x Spieler-Handelsquote beim Handel mit Uran und angereichertem Uran</li><li>Eiznigartige kostenlose Richtlinie: Sirup Kunststoff</li><li>Spielzeughersteller haben doppelte Produktivität</li><li>Spieleentwickler haben 2x Kapazität</li>",
    MapExtraPermitDesc: "Du erhältst %{number} kostenlose Baugenehmigungen durch den einzigartigen Bonus der Karte",
    OsloBonusV3:
        "<li>Ölraffinerien sind freigeschaltet</li><li>Ölraffinerien haben 2x Kapazität</li><li>Die Transportrichlinie 'Elektronisches Öl' ist kostenlos</li><li>Gasaufbereitungsanlagen haben 2x Kapazität</li><li>1x kostenlose Windturbine der Stufe 4</li><li>1x kostenlose Ölquelle der Stufe 8</li><li>1x kostenlose Stufe 2 Ölraffinerie</li><li>1x kostenlose Stufe 2 Gaspumpe</li>",
    ResourceBoosterPercentageV2: "💡 Dieser Betrag beinhaltet %{percent} Boost von benachbarten Ressourcenverstärkern",
    MapleSyrup: "Ahornsirup",
    MapleSyrupFactory: "Ahornsirupfabrik",
    SyrupPlastic: "Sirup Kunststoff",
    SyrupPlasticDesc: "Alle Gebäude, die Kunststoff verwenden, verwenden stattdessen Ahornsirup",
    ResourceBoosterSupplyChain: "Lieferkettenbonus",
    ResourceBoosterSupplyChainDesc:
        "Ressourcenverstärker verbrauchen 2x Strom und Wissenschaftspunkte, aber für jede arbeitende Mine erhöht ein Ressourcenverstärker die Kapazität benachbarter Fabriken, die das Erzeugnis der Mine verbrauchen (die Fabrik sollte nur Lagerbestände verbrauchen).",
    ProductionDiversification: "Produktionsdiversifizierung",
    ProductionDiversificationDesc: "Jeder Gebäudetyp gibt allen Gebäuden 1% zusätzliche Kapazität",
    ExtraPolicyPointsDescV2:
        "Das Policy Center verfügt über die doppelte Konvertierungskapazität von Richtlinienpunkten",
    PowerRequired: "Strom benötigt",
    AchievementVancouver100: "Saftverkäufer",
    AchievementVancouver100Desc: "Verdiene 100 Schweizer Franken in Vancouver in einem Durchgang",
    AchievementVancouver500: "Sirupvertiebler",
    AchievementVancouver500Desc: "Verdiene 500 Schweizer Franken in Vancouver in einem Durchgang",
    AchievementVancouver1000: "Canuck-Eroberer",
    AchievementVancouver1000Desc: "Verdiene 1000 Schweizer Franken in Vancouver in einem Durchgang",
    BarbariansAtTheGate: "Barbaren am Tor",
    BarbariansAtTheGateDesc: "Nutze zwischen den Marktaktualisierungen eine Handelsquote von 1T auf dem Spielermarkt",
    DiversifiedProductions: "Diversifizierte Produktionen",
    DiversifiedProductionsDesc: "Baue 100 verschiedene Gebäudetypen auf einer einzigen Karte",
    RealEstateTycoon: "Immobilien-Tycoon",
    RealEstateTycoonDesc: "Baue 400 Gebäude auf einer einzigen Karte",
    ResourceExplorer2DescV2:
        "Ressourcenfinder produzieren 2x Ertrag, verbrauchen aber 2x Strom. Ressourcenfinder können durch Ressourcenverstärker beeinflusst werden, wenn die Lieferketten-Richtlinie aktiv ist und der Verstärker eine benachbarte Mine mit der gleichen Ressource hat",
    NoTileModifier: "Die Erde ist eine Scheibe",
    NoTileModifierDesc:
        "Alle Zellenmodifikatoren werden 0. Diese Richtlinie wird die Richtlinien (Kraft der Natur) und (Zellenmodifikator Plus) deaktivieren.",
    DoubleTileModifierDescV2:
        "Alle Zellenmodifikatoren x2 - positive als auch negative. Die Richtlinie wird (Die Erde ist Rund - Richtlinie) deaktivieren.",
    TileModifierOutputOnlyDescV2:
        "Zellenmodifikatoren beeinflussen nur die Produktion, anstelle der Produktion und des Verbrauchs, sind aber nur zu 50% effektiv. Die Richtlinie wird (Die Erde ist eine Scheibe - Richtlinie) deaktivieren.",
    QuickLinks: "Direktlinks",
    GetHelp: "HILFE",
    GetHelpBeginnerGuides: "Anfängerhilfen",
    GetHelpSteamGuides: "Andere Hilfen auf Steam",
    GetHelpInGameChat: "Frage im Spielchat",
    GetHelpDiscord: "Trete unserem Discordserver bei!",
    GetHelpWiki: "Community Wiki",
    SelectATile: "Wähle eine Zelle",
    PledgeAmount: "Beitrag %{amount}",
    PledgeValue: "Wert $%{amount}",
    TotalPledgedValue: "Gesamter Beitragswert",
    TotalPledgedValueDesc:
        "Dein erster Beitrag zählt für das Crowdfundingziel. Nachfolgende Beiträge erhöhen den gesamten Beitragswert, zählen aber nicht zum Ziel",
    ReturnOnPledge: "Gewinn bei Erfolg",
    CrowdfundingEndIn: "Endet in %{time}",
    ClaimCrowdfundingReward: "Belohnung einfordern %{amount}",
    PledgeSuccessful: "Du hast %{amount} zum Crowdfunding beigetragen",
    CrowdfundingClaimSuccessful: "Du hast %{amount} Geld abgeholt",
    CrowdfundingAlreadyPledged: "Bereits beigetragen",
    CrowdfundingAlreadyPledgedDesc:
        "Du kannst mehr Ressourcen beisteuern, was deinem Gesamtwert (und die potenzielle Rendite) erhöht, aber nicht auf das Crowdfunding-Ziel angerechnet wird",
    WholesaleCenterProducingOnly: "Großhandelspartner",
    WholesaleCenterProducingOnlyDesc:
        "Bestellungen im Großhandelszentrum enthalten nur Ressourcen, deren Fabriken du gebaut hast (Du musst auch die Anzahl der erforderlichen Ressourcen produzieren, um das Großhandelszentrum freizuschalten).",
    SoftwareCompiler: "Software Compiler",
    SearchEngine: "Suchmaschine",
    SearchEngineCompany: "Suchmaschinenentwickler",
    Navy: "Marine",
    NavyCommand: "Marineführung",
    Battleship: "Schlachtschiff",
    BattleshipFactory: "Schlachtschiffwerft",
    ResourceMovementHide: "Immer ausblenden",
    ResourceMovementShow: "Immer anzeigen",
    ResourceMovementViewport: "Punkte",
    ResourceMovementHighlight: "Bei Markierung",
    ResourceMovementLine: "Linien",
    ResourceMovement: "Ressourcenbewegung",
    ResourceMovementDesc:
        "Du kannst auswählen, wann die Ressourcenbewegungen (Punkte) angezeigt werden sollen. Das Ausblenden kann die Leistung verbessern",
    CrowdfundingCashInWarning:
        "Du hast ausstehende Crowdfundingbeiträge – wenn du in einer neuen Stadt beginnst, verfallen sie",
    ResourceBoosterBannerDescV2:
        "💡 Du hast aktuell %{number} Ressourceverstärker - der wissenschaftliche Input jedes einzelnen wird auf die Anzahl der Ressourcenverstärker skaliert, die du derzeit hast",
    CrowdfundingId: "Crowdfunding %{id}",
    PatchNotes: "Patch Notizen",
    PatchNotesDesc: "Lese, was neu im Update ist",
    PanelPositionLeft: "Links (angeheftet)",
    PanelPositionLeftFloat: "Links (frei)",
    PanelPositionRight: "Rechts (angeheftet)",
    PanelPositionRightFloat: "Rechts (frei)",
    PanelPositionAuto: "Automatisch",
    TimePlayed: "Gespielte Zeit",
    ValuationPerHour: "Wert pro Stunde",
    HighPowerPriority: "Hohe Leistungspriorität",
    HighPowerPriorityDesc: "Ist dies eingeschaltet, zwackt das Gebäude Strom von anderen Gebäuden ab",
    IndustryZone: "Industriezone",
    IndustryZoneDesc:
        "Kombiniere angrenzende Gebäude, die eine Lieferkette bilden und spare Baugenehmigungen",
    IndustryZoneMaxBuildingLevel: "Maximale Gebäudestufe",
    IndustryZoneNotWorkingDesc:
        "Alle angrenzenden Gebäude sollten eine Lieferkette bilden und nicht Teil anderer Industriezonen sein",
    PlayerTradeAutoClaim: "Beanspruche abgeschlossene Handel automatisch",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "Cloud Streaming",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "Supercomputer Labor",
    SuperComputer: "Supercomputer",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "SkyNet",
    RobocarFactory: "Robocarhersteller",
    Robocar: "Robocar",
    WarehouseBuildingPermitSave: "Lagerhausbaugenehmigung",
    WarehouseBuildingPermitSaveDesc: "Für je zwei gebaute Lagerhäuser erhältst du eine kostenlose Baugenehmigung",
    PolicySearchPlaceholder: "Gib den Namen einer Richtlinie ein",
    SwissUpgrade: "Schweizer Upgrade",
    SwissUpgradeDesc: "Schweizer Upgrades sind permanent und werden in die neue Stadt übertragen",
    SwissBoost: "Schweizer Boost",
    SwissBoostDesc:
        "Der Schweizer Boost wirkt nur auf die jetzige Stadt - und muss nach dem Start in einer neuen Stadt' wieder aktiviert werden",
    ProductionMultipliers: "Produktionsmultiplikator",
    MultiplierMapUniqueBonus: "Einzigartiger Kartenbonus",
    MultiplierSwissUpgrade: "Schweizer Upgrade (Permanent)",
    MultiplierSwissBoost: "Schweizer Boost (Aktuelle Stadt)",
    SwissBoostCostDivider: "Schweizer Boost Kostenteiler",
    SwissBoostCostDividerDesc:
        "Teile die Schweizer Boost Kosten durch diesen Wert - funktioniert nur für Multiplikator- und Teilerverbesserungen",
    AirForceCommand: "Luftwaffenführung",
    AirForce: "Luftwaffe",
    StealthFighterFactory: "Tarnkappenbomberfabrik",
    StealthFighter: "Tarnkappenbomber",
    ArmyCommand: "Heeresführung",
    Army: "Heer",
    GreenPeacekeeper: "Green Peacekeeper",
    GreenPeacekeeperDesc:
        "Stelle Heer, Marine, Luftwaffe oder Space Force nur mit erneuerbaren Energien her (Wind/Solar)",
    DotComTycoon: "DotCom Tycoon",
    DotComTycoonDesc:
        "Baue mindestens 1x Stufe 10 Scial Network Inc, 1x Stufe 10 Suchmaschinenfirma, 1x Stufe 10 Skynet Inc und 1x Stufe 10 Musify Inc auf derselben Karte",
    ConstructionNotResearched: "Nicht erforscht",
    OfflineEarningDescV2:
        "Offlineeinkommen basiert auf deiner derzeitigen Forschung, Produktion und dem automatischen Verkauf",
    HighSpeedWarehouse: "Hochgeschwindigkeits-Warenhaus",
    HighSpeedWarehouseDesc:
        "Warenhäuser haben doppelte Kapazität und einen 50% schnelleren Warentransport, aber verbrauchen doppelt so viel Strom",
    IndustryZoneMultiplierDesc: "Industriezonenbonus",
    IndustryZoneMultiplierSwissBoost: "Industriezonenkapazitätsverstärker",
    EarningPerMinuteV2: "Offline-Erwerbsrate",
    OfflineResearchPoint: "Offline-Forschungspunkte",
    WholesaleCenterOrderFasterV2: "Größer, schneller, Großhandel",
    OfflineResearchSwissBoost: "Offline-Forschung",
    OfflineResearchSwissBoostDesc:
        "Forschungspunkte werden auch offline generiert (Basierend auf der Stufe des Forschungslabors, Wissenschaft im Warenhaus und der Offlineerwerbszeit)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Einzigartiges Gebäude: Chipfabrik</li><li>Einzigartiges Gebäude: FaceApp Inc</li><li>Einzigartiges Gebäude: Bitcoin Miner</li><li>Alle Gebäude, die Silikon verbrauchen, haben maximalen Zellenmodifikator</li><li>Solarmodule produzieren doppelt so viel Strom</li><li>Siliziumminen produzieren doppelt so viel</li>",
    RotterdamBonusV2:
        "<li>Stahlwerke haben 2x Kapazität</li><li>Edelstahlanlagen haben 2x Kapazität</li><li>Kostenloser Eisentransport</li><li>Stahltransport kostet 50 % weniger Kraftstoff</li><li>Beginne mit 2x automatischer Verkaufsmenge</li><li>Die Richtlinie (Die Erde ist eine Scheibe) ist kostenlos</li>",
    ChipManufacturer: "Chipfabrik",
    SnapTokInc: "SnapTok Inc",
    FaceAppInc: "FaceApp Inc",
    BitcoinMiner: "Bitcoin Miner",
    GalvanicBatteryFactory: "Galvanische-Batterie-Fabrik",
    BaseProductionMultiplier: "Basisproduktion",
    ShowBreakdown: "Zeige Unterteilung",
    HideBreakdown: "Verstecke Unterteilung",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Jede Stufe einer Lieferkettede in der Industriezone gibt seinen Kapazitätsboost allen anderen Gebäude in der Zone",
    IndustryZoneBuildingPermitDesc:
        "Wenn eine Industriezone N Stufe and Produktion hat, dann gibt es N-2 Baugenehmigungen umsonst",
    CrowdfundingBackersReturn: "Investoren: %{backers}, Derzeitiger Gewinn: %{return}",
    CrowdfundingBackersNeeded: "%{backers} mehr Investoren",
    CrowdfundingReturnBonus: "+%{return} Gewinn",
    ReturnOnPledgeDescV2:
        "Dein Gewinn ergibt sich aus deinem gesamten Beitrag, multipliziert mit den Gewinnraten aller Ressourcen. Je mehr du in eine Ressource investierst, desto höher wird der Gewinn sein.",
    AchievementSanJose100: "Venture Hobbyist",
    AchievementSanJose100Desc: "Verdiene 100 Schweizer Franken in San Jose in einem Durchgang",
    AchievementSanJose500: "Venture Enthusiast",
    AchievementSanJose500Desc: "Verdiene 500 Schweizer Franken in San Jose in einem Durchgang",
    AchievementSanJose1000: "Venture Capitalist",
    AchievementSanJose1000Desc: "Verdiene 1000 Schweizer Franken in San Jose in einem Durchgang",
    AchievementCrowdfundingTycoon: "Crowdfunding Tycoon",
    AchievementCrowdfundingTycoonDesc: "Trage Ressourcen im Wert von 1Qa zu einem einzigen Crowdfunding-Ziel bei",
    AchievementCashIsKing: "Cash Is King",
    AchievementCashIsKingDesc: "Habe 1Qa Bargeld in einem Durchgang",
    AchievementPowerTycoon: "Power Tycoon",
    AchievementPowerTycoonDesc: "Erzeuge 1 Gigawatt Strom in einem Durchgang",
    PlayerTradeFilteringNResources: "Filtert %{n} Ressourcen",
    PlayerTradeFilterResources: "Filtere Ressourcen",
    PlayerTradeFilterClear: "Filter löschen",
    ResourceExplorerAll: "Erforsche alle Ressourcen",
    ResourceExplorerAllDesc:
        "Ressourcenfinder können alle Ressourcen produzieren, auch die, die nicht auf der Karte vorkommen (schaltet NICHT die relevanten Technologien frei)",
    ShowResourceInTopBar: "Zeige in der oberen Leiste",
    LeaderboardOptOutDescV2:
        "Du wirst nicht mehr auf der Bestenliste angezeigt. Der Spielerhandel wird ausgeschaltet. ACHTUNG: Wenn du wieder auf der Bestenliste erscheinen willst, muss dein Spiel zurückgesetzt werden",
    PolicyPointNoCopperDesc:
        "💡 Diese Karte hat keine Kupfervorkommen, du kannst 'Al Schaltkreis' aktivieren um weitere Technologien freizuschalten",
    Pumpkin: "Kürbis",
    PumpkinBattery: "Kürbisbatterie",
    PumpkinBatteryDesc: "Alle Gebäude, die Batterien verbrauchen, nutzen stattdessen Kürbisse (Kostenlose Richtlinie)",
    PumpkinSteel: "Kürbisstahl",
    PumpkinSteelDesc: "Alle Gebäude, die Stahl verbrauchen, nutzen stattdessen Kürbisse (Kostenlose Richtlinie)",
    RequireExpansionPack2: "Erweiterung 2",
    ExpansionPack2: "Erweiterung 2",
    RequireExpansionPack2Desc: "Das ist nur für die Erweiterung 2 verfügbar",
    Reindeer: "Rentier",
    ReindeerSilicon: "Rentier-Silizium",
    ReindeerSiliconDesc: "Alle Gebäude, die Silizium verbrauchen, nutzen stattdessen Rentiere (Kostenlose Richtlinie)",
    ReindeerAluminum: "Rentier-Aluminium",
    ReindeerAluminumDesc:
        "Alle Gebäude, die Aluminium verbrauchen, nutzen stattdessen Rentiere (Kostenlose Richtlinie)",
    SantaClauseIsComing: "Der Weihnachtsmann kommt :^)",
    SantaClauseIsComingDesc:
        "Weihnachtsmannfabriken nutzen Spielzeug und Rentiere, Wissenschaft und Kultur. Weihnachtsmannfabriken haben maximalen Zellenmodifikator. Spielzeugfabriken produzieren zusätzlich zu Spielzeug auch Rentiere (kostenlose Richtlinie)",
    MetaRebranding: "Meta Rebranding",
    MetaRebrandingDesc:
        "Social Network Inc wird zu Meta Inc umbenannt und verbraucht stattdessen Internet, Computerspiele, Supercomputer, Bitcoin und Dogecoin.",
    MetaInc: "Meta Inc",
    ImportSave: "Importiere Speicherstand",
    ClearMyTrades: "Spielstand zurücksetzen",
    SaveVersionTooNew:
        "Dein Speicherstand ist aus der Version: %{saveVersion}, dein Spiel ist auf Version %{gameVersion}. Aktualisiere zuerst dein Spiel",
    LeaderboardByFlag: "Bewertung nach Spielerflagge",
    LeaderboardByMap: "Bewertung nach Karte",
    LeaderboardByFlagPlayerFlag: "Flagge",
    LeaderboardByFlagPayerCount: "Spielerzahl",
    LeaderboardByFlagPayerValuationPerHour: "V/H",
    LeaderboardByFlagPayerSwissMoney: "Schweizer Franken",
    PlayerTradePriceFilter: "Preisfilter",
    PlayerTradeFilterBetterThanMarket: "Besser als der Markt",
    PlayerTradeFilterAll: "Alles",
    PlayerTradeFilterBestPrice: "Bester Preis",
    CrowdfundingTotalPledgdeValueTooLarge:
        "Dein Beitrag fürs Crowdfunding darf deine derzeitige Marktkapitalisierung nicht überschreiten",
    BuildingSourceAuto: "Automatische Quelle",
    BuildingSourceManual: "🔍 Manuelle Quelle",
    BuildingSourceReset: "Zurücksetzen",
    BuildingSourceSelecting: "Klicke auf die Karte...",
    BuildingSourceSetOverride: "Überschreiben",
    BuildingSourceFallback: "Manuelle Quellen",
    BuildingSourceFallbackDesc:
        "Wie sollte das Gebäude den Eingang transportieren, wenn die manuelle Quelle nicht genug hat? Überspringen - nicht transportieren; Restposten - transportiere, was übrig ist; Neu - nutze automatische Quellen um eine neue Quelle zu finden",
    BuildingSourceFallbackSkip: "Überspringen",
    BuildingSourceFallbackDrain: "Restposten",
    BuildingSourceFallbackAuto: "Neu",
    BuildingSourceFallbackMarker: "(Restbestände)",
    BuildingSourceFallbackMarkerDesc: "Der manuellen Quelle fehlt es an Ressourcen, es wird auf andere Quellen zurückgegriffen",
    BuildingSourceInvalid: "Deine ausgewählte Quelle ist ungültig, wähle ein gültige Zelle aus.",
    RandomIsland: "Zufällige Insel",
    RandomIslandBonus:
        "<li>Die Karte ist jedes Mal anders wenn du neu beginnst</li><li>Kartengröße, Zellentyp, Ressourcenvorkommen und einzigartige Boni werden zufällig ausgewählt</li><li>Für Kartenneustarts gibt es eine Wartezeit von 5 Minuten.</li>",
    RandomIslandBonusDesc:
        "Der einzigartige Bonus auf der zufälligen Insel verändert sich jedes Mal, wenn du auf der Karte neu startest.",
    RandomIslandBonusCapacity: "%{building} hat %{multiplier}x Kapazität",
    RandomIslandBonusProductivity: "%{building} hat %{multiplier}x Produktivität",
    RandomIslandBonusResources: "Resourcenvorkommen auf dieser Karte: %{deposits}",
    ValuationPerActiveMinute: "Bewertung per aktiver Minute",
    Perth: "Perth",
    GV: "Geothermiequelle",
    GeothermalPowerPlant: "Hochenthalpie-Lagerstätten",
    AdjacentExplorer: "Angrenzender Bonus: Forscher",
    AdjacentExplorerDesc:
        "Ressourcenfinder haben doppelte Produktiviät, wenn die Ressource, die es produziert, angrenzt. (Kostenlose Richtlinie)",
    FactoryMining: "Industrialisierte Mine",
    FactoryMiningDesc:
        "Eine Produktionsstätte kann Vorkommen direkt auf der Zelle abbauen, wenn es diese Ressource auch verbraucht (Kostenlose Richtlinie)",
    FactoryMiningBanner: "Dieses Gebäude baut %{resource} direkt von dieser Zelle ab",
    WarehouseSourceWeight: "Gewicht: %{weight}",
    YAxisStartsFromZero: "Y-Achse startet bei 0",
    YAxisStartsFromZeroDesc: "Die Y-Achse jeder Grafik fängt immer bei 0 an, anstatt automatisch angepasst zu werden",
    OwnDLC: "Du besitzt %{number}x Erweiterung(en)",
    GeneralServerSuccessMessage: "Deine Anfrage wurde erfolgreich ausgeführt",
    GeneralServerErrorMessage: "Serverfehlermeldung: %{error}",
    WarehouseInputRoutes: "Eingaberouten",
    WarehouseOutputRoutes: "Ausgaberouten",
    InputCapacity: "benötigte Materialien",
    MultipleSources: "Mehrere Quellen",
    MultipleSourcesDesc: "Das Gebäude bezieht während eines Kreifslaufes Ressourcen von mehreren Quellen",
    Water: "Wasser",
    KansasCity: "Kansas City",
    Dam: "Staudamm",
    DamDesc: "Staudämme fluten angrenzende Zellen und verwandeln sie zu Wasser",
    Farmland: "Acker",
    FarmlandDesc: "Baue Pflanzen auf Wasserzellen an",
    Storage: "Lagerung",
    Rice: "Reis",
    Corn: "Mais",
    Wheat: "Weizen",
    Soybean: "Sojabohne",
    Sugarcane: "Zuckerrohr",
    Vegetable: "Gemüse",
    FarmlandProduce: "Ernte",
    FarmlandOfflineFarming: "Offline-Landwirtschaft",
    FarmlandOfflineFarmingDesc:
        "Äcker auf natürlichen Wasserquellen produzieren auch offline weiter. Wird durch Schweizer Upgrades und Offlineerwerbszeit beeinflusst.",
    FarmlandProductionDesc: "💡 Äcker arbeiten nur 5 von 10 Sekunden - alle Kreisläufe sind verbunden",
    WaterPump: "Wasserpumpe",
    Greenhouse: "Gewächshaus",
    GreenhouseDesc: "Baue eine Pflanze deiner Wahl an",
    WaterEntityLevelTooHighDesc:
        "Die Gebäudestufe ist höher als die des anliegenden Staudammes. Verbessere deinen Staudamm.",
    AirLiquidizer: "Luftverflüssiger",
    CapacitorFactory: "Kondensatorfabrik",
    Capacitor: "Kondensator",
    OfflineProduction: "Offlineproduktion",
    OfflineProductionDesc: "Wenn dieses Gebäude mit Kondensatoren versorgt wird, produziert es auch offline.",
    Moderator: "Moderator",
    FlourMill: "Getreidemühle",
    Flour: "Mehl",
    FlourMillAdjustMix: "Mehlmischung anpassen",
    RiceFlour: "100% Glutenfrei",
    RiceFlourDesc: "Getreidemühlen verbrauchen Reis statt Weizen.",
    Bread: "Brot",
    Bakery: "Bäckerei",
    Fodder: "Futter",
    FodderFactory: "Futterhersteller",
    SugarRefinery: "Zuckerraffenerie",
    RefinedSugar: "raffinierter Zucker",
    ShowSupplyChain: "Lieferkette",
    ShowSupplyChainDesc: "Wenn du ein Gebäude hervorhebst, wird die gesamte zugehörige Lieferkette markiert.",
    Cake: "Kuchen",
    ChooseARecipe: "Wähle ein Rezept",
    ChickenFarm: "Geflügelzuchtbetrieb",
    Chicken: "Huhn",
    Egg: "Ei",
    CowFarm: "Rinderzuchtbetrieb",
    Beef: "Rindfleisch",
    Milk: "Milch",
    DairyFactory: "Molkerei",
    Cheese: "Käse",
    Cookie: "Keks",
    Butter: "Butter",
    UnlockAtLevel: "Freigeschaltet ab Stufe %{level}",
    FastFoodChain: "Fast Food-Kette",
    Burger: "Burger",
    Sandwich: "Sandwich",
    StandbyMode: "Energiesparmodus",
    StandbyModeDesc:
        "Das Spiel wird weiterhin im Hintergrund laufen, aber keine Grafiken mehr rendern. Grafikkarte und CPU werden entlastet",
    StandbyModeOn: "Ruhemodus an",
    StandbyModeOnDesc: "Das Spiel läuft im Energiesparmodus. Drücke eine beliebige Taste um zum Spiel zurückzukehren.",
    PigFarm: "Schweinezuchtbetrieb",
    Pork: "Schweinefleisch",
    SausageFactory: "Metzgerei",
    Sausage: "Wurst",
    Hotdog: "Hotdog",
    BatchOperationDesc:
        "Dies wird auf %{number} Gebäude angewandt. Die vorraussichtlichen Baukosten belaufen sich auf $%{cost}. Möchtest du fortfahren?",
    BatchOperationResult: "Der Bau wurde für %{success} Gebäude erfolgreich ausgeführt",
    StreamingMakeMeDiscoverable: "Mach mich entdeckbar",
    StreamingMakeMeDiscoverableDesc:
        "Erlaube es anderen Spielern, deinem Spiel zuzuschauen. Die Verbindung basiert auf P2P und es wird nur das Spiel übertragen. Es wird weder auf Mikrofon, noch auf deine Kamera zugegriffen",
    StreamAutoApprove: "Öffentliche Übertragung",
    StreamAutoApproveDesc: "Erlaubt es Spielern deine Übertragung anzuschauen ohne individuelle Anfragen stellen zu müssen.",
    StreamingWatch: "Zusehen",
    StreamingStop: "Anhalten",
    StreamingPlayerDisconnected: "%{player} hat deine Übertragung verlassen",
    StreamingPlayerRejected: "%{player} hat deine Übertragungsanfrage abgelehnt",
    StreamingPlayerRequested:
        "%{player} hat angefragt, deiner Übertragung zuzuschauen. Gehe zum Hauptquartier, um anzunehmen oder abzulehnen",
    StreamingSettings: "Übertragungseinstellungen",
    StreamingAvailableStreams: "Verfügbare Übertragungen",
    StreamingAudience: "Zuschauer",
    StreamingStopStream: "Nicht mehr für diesen Zuschauer streamen",
    StreamingAcceptStream: "Annehmen",
    StreamingRejectStream: "Ablehnen",
    StreamingStopStreamDesc: "Nicht mehr für diesen Zuschauer streamen",
    StreamingConnectionFailed:
        "Verbindung konnte nicht aufgebaut werden - dein Netzwerk unterstützt wahrscheinlich keine P2P-Verbindungen",
    Pizza: "Pizza",
    StreamingStartRecord: "Aufnahme starten",
    StreamingRecordCamera: "Nehme einen Director´s Cut auf",
    StreamingRecordCameraDesc:
        "Nehmen einen 10s Director´s Cut auf - die Kamera geht auf maximalen Zoom und schwenkt langsam raus",
    StreamingStopRecord: "Aufnahme stoppen",
    StreamingRecordingReady: "Aufnahme ist bereit",
    StreamingRecordingReadyDesc: "Du kannst deine Aufnahme speichern und mit einem kompatiblen Videospieler abspielen.",
    StreamingRecordingSave: "Speichern als",
    Lantern: "Laterne",
    LunarNewYear22: "Jahr des Tigers",
    LunarNewYear22Desc:
        "Alle Gebäude, die Papier verbrauchen, nutzen stattdessen Laternen und haben 2x Kapazität. Papierfabrik und Papierakademien produzieren stattdessen Kultur.",
    PaperAcademy: "Papierakademie",
    FriedRice: "gebratener Reis",
    Highlight: "🔍 Markieren",
    BatchMode: "Batchmodus",
    BatchModeAll: "Alle",
    BatchModeAdjacent: "Angrenzend",
    BatchModeCluster: "Gruppe",
    BatchUpgradeToLevelX: "Zur Stufe %{level}",
    ApplyToBatch: "Auf %{batch} anwenden",
    BatteryRecycler: "Batterierecycler",
    BatteryShell: "Batteriegehäuse",
    StartInANewCity: "Starte in einer neuen Stadt",
    StartInANewCityFinePrint: "(Oder starte deine derzeitge Stadt neu)",
    BatteryFuelDesc:
        "💡 Nachdem Batterien als Kraftstoff verwendet wurden, werden diese zu Batteriegehäusen. Du kannst Batterierecycler bauen oder sie wieder aufladen",
    FriedChicken: "Gebratenes Hühnchen",
    Coffee: "Kaffee",
    Cocoa: "Kakao",
    CornSyrup: "Sirup",
    CornSyrupDesc: "Zuckerraffinerien produzieren Zucker mit Mais anstatt Zuckerrohr",
    Crop: "Ernte",
    FishPond: "Fish Pond",
    Fish: "Fisch",
    LoadGameErrorRetry: "Wiederholen",
    LoadGameErrorHardReset: "Hard Reset",
    FontSizeScaling: "Schriftgröße",
    FontSizeScalingDesc:
        "Verändert die Schriftgröße. Die Benutzeroberfläche könnte komisch aussehen. Benötigt Neustart.",
    FrozenVegetable: "Gefrohrenes Gemüse",
    MilkPowder: "Milchpulver",
    CannedFish: "Dosenfisch",
    CocoaPowder: "Kakaopulver",
    FrozenChicken: "Gefrohrenes Hühnchen",
    FrozenPork: "Gefrohrenes Schweinefleisch",
    CannedBeef: "Büchsenrindfleisch",
    FoodProcessingPlant: "Lebensmittelverarbeitungsbetrieb",
    KansasCityBonus:
        "<li>Äcker und Gewächshäuser haben doppelte Produktivität</li><li>Der Maistransport ist kostenlos</li><li>Für jede Stufe verstärken Staudämme angrenzende Äcker um 5%</li><li>Je zwei Äcker bieten eine kostenlose Baugenehmigung</li><li>Die 'Die Sonne geht nie unter' Richtlinie lässt Äcker 100% der Zeit arbeiten (auch offline)</li><li>Doppelte Handelsquota beim Handeln von Mais</li><li>Lebensmittelverarbeitungsbetrieb sind freigeschaltet</li>",
    KansasCityHydroDamBoost: "Kansas City einzigartiger Bonus: Ein Staudamm verstärkt angrenzende Äcker um %{boost}",
    PerthGeothermalPowerPlantBoost:
        "Perth einzigartiger Bonus: Die Hochenthalpie-Lagerstätte gibt %{boost} Boost an angrenzende Stahlproduzenten ab.",
    PerthBonus:
        "<li>Produktionsrotation läuft, anders als in anderen Städten, gegen den Uhrzeigersinn</li><li>Einzigartiges Gebäude: Geothermische Lüftung</li><li>Einzigartiges Gebäude: Hochenthalpie-Lagerstätte</li><li>Einzigartige Richtlinie: Nachbarschaftsbonus Explorer (FREE), Factory Mining (FREE)</li>",
    Biofuel: "Biotreibstoff",
    RioDeJaneiro: "Rio de Janeiro",
    RioDeJaneiroBonus:
        "<li>Einzigartiger Kraftstoff: Bio-Treibstoff</li><li>Schweine-, Rinder-, und Hühnerzuchtbetriebe produzieren extra Bio-Kraftstoff</li><li>Einzigartiges Gebäude: Biokraftstoff-Kraftwerk</li><li>Einzigartiges Gebäude: Cristo Redentor</li><li>Ressourcenverstärker können Schweine-, Rinder-, und Hühnerzuchtbetriebe verstärken. </li><li>Forstbetriebe produzieren 2x Holz</li><li>Sägewerke haben 2x Kapazität</li><li>Gefrohrenes Hühnchen, Gefrohrenes Schweinefleisch und Gefrohrenes Rinderfleich haben doppelte Handelsquote</li>",
    BiofuelPowerPlant: "Biotreibstoff-Kraftwerk",
    CristoRedentor: "Cristo Redentor",
    CristoRedentorBanner:
        "Cristo Redentor gibt jedem Gebäude mit gleicher oder niedrigerer Stufe Angrenzungsbonus. Der Kulturverbrauch wächst exponential mit der Anzahl an gebauten Cristo Redentor.",
    CristoRedentorDesc: "Verbraucht Kultur und verbessert jegliche angrenzenden Gebäude",
    Istanbul: "Istanbul",
    Wormhole: "Wurmloch",
    WavesSurvived: "überlebte Wellen",
    NumberOfWormholes: "Anzahl der Wurmlöcher auf der Karte",
    NextWave: "Nächste Welle",
    NextWaveUnitHP: "Lebenspunkte der Einheiten",
    NextWaveTotalCount: "Gesamte Einheiten",
    NextWaveTotalCountDesc: "Gesamtanzahl an Einheiten, die aus jedem Wurmloch kommen",
    NextWaveSpeed: "Bewegungsgeschwindigkeit",
    NextWaveSpawnDelay: "Spawnfrequenz",
    NextWaveSpawnDelayValue: "Alle %{number}s",
    NextWaveBonusMultiplier: "Bonusmultiplikator",
    NextWaveBonusMultiplierValue: "%{number}x",
    NextWaveTotalDamageNeeded: "Benötigter Gesamtschaden",
    NextWaveTotalReward: "Gesamtbelohnung",
    StartWave: "Welle starten",
    WaveSpawned: "Angreifer sind erschienen",
    WaveEliminated: "Besiegt",
    WaveFailed: "Verloren",
    WaveRetry: "Wiederholen",
    WaveForfeit: "Aufgeben",
    Damage: "Schaden",
    DefenseCommandConvert: "Umwandeln",
    DefenseModule: "Verteidigungsmodul",
    DefenseModuleAddOne: "Füge ein Verteidigungsmodul hinzu",
    DefenseModuleRange: "Reichweite",
    DefenseModuleDamage: "Schaden",
    DefenseModuleBulletSpeed: "Projektilgeschwindigkeit",
    DefenseModuleAttackSpeed: "Angriffsgeschwindigkeit",
    DefenseModuleUpgrade: "Verbesserung",
    DefenseModuleMaxUpgrade: "Maximale Verbesserung",
    DefenseModuleCriticalDamageChance: "kritische Trefferwahrscheinlichkeit",
    DefenseModuleCriticalDamageChanceShort: "Krit Dmg %",
    DefenseModuleCriticalDamageMultiplier: "Kritischer-Schaden-Multiplikator",
    DefenseModuleCriticalDamageMultiplierShort: "Krit Dmg x",
    DefenseModuleBaseModule: "Basismodul",
    DefenseCommand: "Oberkommando der Verteidigung",
    DefenseCommandDesc: "Verursache Schaden mit Waffen und verteidige deine Basis gegen Eindringlinge",
    PathBlocked:
        "Du kannst keine Gebäude auf dieser Zelle bauen, da dadurch alle möglichen Wege von den Wurmlöchern zum Hauptquartier blockiert werden",
    WaveInProgressBuildRemoveDisabled:
        "Du kannst keine Gebäude auf dem Weg bauen und keine Gebäude während der Invasionswelle verkaufen",
    ExportSaveForTransfer: "Übertrage deinen Speicherstand",
    ExportSaveForTransferDesc:
        "Wähle diese Option, wenn du deinen Speicherstand auf ein anderes Gerät übertragen willst. Dein Handelsrecht wird auf diesen Spielstand transferiert - du kannst wieder handeln, nachdem du den Speicherstand importierst. Auf deinem derzeitigen Gerät kannst du erst wieder nach einer Wartezeit handeln.",
    ExportSaveForBackup: "Backup für deinen Speicherstand",
    ExportSaveForBackupDesc:
        "Wähle diese Option, wenn du ein Backup deines Fortschrittes machen will. Dein derzeitiges Gerät behält das Handelsrecht - Das Backup zu importieren stellt das Handelsrecht erst nach einer Wartezeit wieder her",
    RightToTradeValid: "Handelsrecht",
    RightToTradeInvalid: "Kein Handelsrecht",
    RightToTradeInvalidDesc:
        "Dein Handelsrecht wurde auf einen anderen Speicherstand übertragen - Du musst den Speicherstand importieren, um dein Handelsrecht wiederherzustellen. Du kannst dein Handelsrecht auch ohne Speicherstand wiederherstellen, aber du kannst erst nach einer Wartezeit wieder handeln und dein exportierter Speicherstand verliert sein Handelsrecht.",
    ForceRestoreRightToTrade: "Erzwinge Wiederherstellung (%{cooldown}-hour cooldown)",
    ImportSaveRestoreFail: "Verbindungsfehler, prüfe deine Internetverbindung",
    DefenseCommandConvertDesc: "Verwandle Ressourcen, basierend auf Handelszentrumspreisen, in Schaden um.",
    MousewheelSensitivity: "Mausradempfindlichkeit",
    MousewheelSensitivityDesc: "Passe die Sensitivität für das Mausrad beim rein- und rauszoomen an.",
    PlayerTradeFilterWhatIHave: "Vorrätig",
    PathTemporarilyBlocked:
        "Du kannst während einer aktiven Angriffswelle keine Gebäude bauen. Versuche es erneut, wenn die Welle abgeschlossen wurde.",
    MoveBuilding: "Gebäude bewegen",
    MoveBuildingInvalidTarget: "Gebäude konnte nicht verschoben werden. Ausgewählte Zelle ist ungültig.",
    MoveBuildingMoving: "Wähle eine leere Zelle...",
    WaveAutoNext: "Automatischer Start",
    WaveAutoNextDesc: "Starte automatisch eine neue Welle, nachdem du eine andere besiegt und deinen Gewinn eingestrichen hast."
    IstanbulBonus:
        "<li>Tower-Defense-Modus: Konvertiere deine Waffen zu Schaden, um Angriffswellen abzuwehren und zusätzliches Geld zu verdienen/li><li>Army commands haben 2x Kapazität</li><li>Panzerwerke haben 2x Kapazität</li><li>Waffenfabriken haben 2x Kapazität</li><li>Fernlenkgeschossfabriken haben 2x Kapazität</li><li>Sprengstoffhersteller haben 2x Produktivität</li>",
    PlayerTradeCancelTitle: "Handel abbrechen?"
    PlayerTradeCancelDescV2: "Der auf diesen Handel gezahlte Tarif wird nicht zurück erstattet"
    PlayerTradeCancelYes: "Handel abbrechen"
    PlayerTradeCancelNo: "Nicht abbrechen"
    SteamAutoCloudBackupDescV3:
        "Your latest progress is saved to Steam Cloud. The game also backs up every 10 minutes - you can force a backup at any time. Loading a backup will lose the right to trade and require a force restoration (subject to cooldown)",
    BuyFromTradeCenter: "Am Spielermarkt einkaufen",
    BuyFromTradeCenterBestBid: "Bester Verkaufspreis am Spielermarkt",
    BuyFromTradeCenterBestAsk: "Bester Ankaufspreis am Spielermarkt",
    BuyFromTradeCenterAveragePrice: "Durchschnittlicher %{price}",
    PlayerTradesAvailable: "%{number} verfügbare Handelsangebote von Spielern",
    SettingsShowInToolbar: "In Übersichtsleiste anzeigen",
    AccountVerification: "Verifizierung",
    AccountAuthenticated: "Verifiziert",
    AccountNotAuthenticated: "Nicht verifiziert",
    AccountTrusted: "Trusted Account",
    AccountLimited: "Eingeschränkter Account",
    AntiCheatPass: "Anti-Cheat Pass",
    AntiCheatFail: "Anti-Cheat Fail",
    AchievementIstanbul100: "Leo der Große",
    AchievementIstanbul100Desc: "Verdiene in einem einzigen Durchlauf 100 Schweizer Franken in Istanbul",
    AchievementIstanbul500: "Justinian der Große",
    AchievementIstanbul500Desc: "Verdiene in einem einzigen Durchlauf 500 Schweizer Franken in Istanbul",
    AchievementIstanbul1000: "Konstantin der Große",
    AchievementIstanbul1000Desc: "Verdiene in einem einzigen Durchlauf 1000 Schweizer Franken in Istanbul",
    AchievementPerth100: "Pademelon",
    AchievementPerth100Desc: "Verdiene in einem einzigen Durchlauf 100 Schweizer Franken in Perth",
    AchievementPerth500: "Wallaby",
    AchievementPerth500Desc: "Verdiene in einem einzigen Durchlauf 500 Schweizer Franken in Perth",
    AchievementPerth1000: "Kangaroo",
    AchievementPerth1000Desc: "Verdiene in einem einzigen Durchlauf 1000 Schweizer Franken in Perth",
    AchievementKansasCity100: "Maiskolben",
    AchievementKansasCity100Desc: "Verdiene in einem einzigen Durchlauf 100 Schweizer Franken in Kansas City",
    AchievementKansasCity500: "Corn Dog",
    AchievementKansasCity500Desc: "Verdiene in einem einzigen Durchlauf 500 Schweizer Franken in Kansas City",
    AchievementKansasCity1000: "Popcorn",
    AchievementKansasCity1000Desc: "Verdiene in einem einzigen Durchlauf 1000 Schweizer Franken in Kansas City",
    AchievementRioDeJaneiro100: "Leblon",
    AchievementRioDeJaneiro100Desc: "Verdiene in einem einzigen Durchlauf 100 Schweizer Franken in Rio de Janeiro",
    AchievementRioDeJaneiro500: "Barra da Tijuca",
    AchievementRioDeJaneiro500Desc: "Verdiene in einem einzigen Durchlauf 500 Schweizer Franken in Rio de Janeiro",
    AchievementRioDeJaneiro1000: "Copacabana",
    AchievementRioDeJaneiro1000Desc: "Verdiene in einem einzigen Durchlauf 1000 Schweizer Franken in Rio de Janeiro",
    AchievementRandomIsland100: "Bernoulli",
    AchievementRandomIsland100Desc: "Verdiene in einem einzigen Durchlauf 100 Schweizer Franken auf einer zufälligen Insel",
    AchievementRandomIsland500: "Poisson",
    AchievementRandomIsland500Desc: "Verdiene in einem einzigen Durchlauf 500 Schweizer Franken auf einer zufälligen Insel",
    AchievementRandomIsland1000: "Gauss",
    AchievementRandomIsland1000Desc: "Verdiene in einem einzigen Durchlauf 1000 Schweizer Franken auf einer zufälligen Insel",
    AchievementFishPond200: "Admiral of the Fish Pond",
    AchievementFishPond200Desc: "Baue 200 Fish Ponds im einem einzigen Spieldurchlauf",
    Photogram: "Fotogramm",
    FineDiningRestaurant: "Gehobenes Restaurant",
    Sushi: "Sushi",
    Pastry: "Gebäck",
    HappyMeal: "Happy Meal",
    Whopper: "Whopper",
    DrinkFactory: "Getränkelieferant",
    SoftDrink: "Erfrischungsgetränk",
    Alcohol: "Alkohol",
    Wine: "Wein",
    Cocktail: "Cocktail",
    ThreeCourseMeal: "3-Gänge Menü",
    SixCourseMeal: "6-Gänge Menü",
    NineCourseMeal: "9-Gänge Menü",
    IndustryZoneCapacityBoostPermanent: "Bonus Industriezone (Permanent)",
    IndustryZoneCapacityBoostThisRun: "Bonus Industriezone (In diesem Durchgang)",
    IndustryZoneMaxBuildingLevelDesc: "Max. Gebäudestufe, die von dieser Industriezone beeinflusst wird",
    IndustryZoneHelp: "Wie funktionieren Industriezonen?",
    IndustryZoneProductivityBoost: "Industriezonen Plus",
    ExtraBuildingPermit: "Zusätzliche Baugenehmigungen",
    ExtraBuildingPermitDesc:
        "Kaufe zusätzliche Baugenehmigungen für deine aktuelle Karte - Dies wird die Kostenkurve nicht erhöhen",
    PanelPositionDescV2:
        "Zeige das Seitenfenster links, rechts oder automatisch (hängt von der selektierten Zelle ab) an. Funktioniert nur im Landscape-Modus",
    PanelHeight: "Fensterhöhe",
    PanelHeightDesc:
        "Wähle die Höhe des Fensters. Funktioniert nur im Porträtmodus auf mobilen Geräten. NEULADEN ERFORDERLICH",
    AllowPortraitMode: "Porträtmodus",
    AllowPortraitModeDesc:
        "Aktiviert den Porträtmodus (experimentell). Der Bildschirm wird, basierend auf den Sensoren und Einstellungen deines mobilen Gerätes, gedreht.",
    IndustryZoneProductivityBoostDesc:
        "Alle 10 Level einer Industriezone erzeugen einen 10% Ausgabeboost für zugehörige Gebäude",
    Auckland: "Auckland",
    AucklandBonus:
        "<li>All Ressourcenvorkommen sammeln sich in der Form Neuseelands im Kartenzentrum.</li><li>Einzigartiges Gebäude: Hydro Power Plant</li><li>Einzigartige Richtlinie: Minenverstärker</li><li>Einzigartige Richtlinie: Elektrischer Fischteich</li><li>Fish Ponds können auf jeder Zelle gebaut werden</li>",
    MineBooster: "Minenverstärker",
    MineBoosterDesc:
        "Eine arbeitende Mine verstärkt benachbarte Minen und Produktionsstätten, die deren Erzeugnisse verbrauchen, um 100%.",
    HydroPowerPlant: "Hydro Power Plant",
    ElectricFishPond: "Elektrischer Fischteich",
    ElectricFishPondDesc: "Jede arbeitende hydro power plant erhöht die Kapazität aller Fischteiche um 20%",
    AccountLimitedDescV2: "Dein Konto erfüllt die Plattformanforderungen nicht",
    AccountLimitedActionV2: "Lese die FAQ über limitierte Accounts",
    CropOutputx2: "Neumodischer Dünger",
    CropOutputx2Desc: "Äcker und Gewächshäuser erbringen 2x Ernte, aber der Erntetransport kostet 2x Kraftstoff.",
    MeatProductionx2: "Steroide für alle",
    MeatProductionx2Desc:
        "Geflügel-, Schweine-, und Rinderzuchtbetriebe, sowie Fischteiche und Futterhersteller haben 2x Kapazität, aber nutzen 2x Strom",
    HydroFarming: "Hydro Farming",
    HydroFarmingDesc: "Jeder arbeitende Staudamm erhöht die Kapazität aller Äcker und Gewächshäuser um 20%",
    ExtraTradeQuota: "Extra Handelsquote",
    ExtraTradeQuotaDesc: "Die Handelsquote beträgt 1% deines Marktwerts - Diese Richtlinie gewährt zusätzliche %",
    ProduceAllCrops: "Grüner Daumen",
    ProduceAllCropsDesc: "Äcker und Gewächshäuser können alle Pflanzen, einschließlich derer, die nicht auf der Karte vorhanden sind, anbauen",
    ResearchAgreement: "Forschungsübereinkunft",
    ResearchAgreementDesc: "Jeder Handel mit einem individuellen Spieler gewährt 10 Minuten Forschungszeit",
    NewsEffectx2V2: "Pressekonferenz",
    NewsEffectx2DescV2: "Alle Marktneuheiten sind 50% effektiver",
    AutoSellCapacityMultiplierV2: "Zusätzliche Verkaufsmenge",
    AutoSellCapacityMultiplierDescV2: "Erlaubt dir, größere Mengen zu verkaufen",
    AutoSellCapacity: "automatische Verkaufsmenge",
    AutoSellCapacityDescV2:
        "Maximale Menge an Ressourcen, die beim automatischen Verkauf pro Sekunde und Ressource gehandelt werden kann, gemessen als Prozentsatz der Gesamtproduktion dieser Ressource",
    AutoSellCapacityExtraPercentageFromSwiss: "Extra Percentage from Swiss Upgrade and Boost: %{n}%",
    BaselineAutoSellCapacity: "Baseline auto sell capacity: %{amount}",
    AchievementAuckland100: "Hoiho",
    AchievementAuckland100Desc: "Verdiene in einem einzigen Durchlauf 100 Schweizer Franken in Auckland",
    AchievementAuckland500: "Whio",
    AchievementAuckland500Desc: "Verdiene in einem einzigen Durchlauf 500 Schweizer Franken in Auckland",
    AchievementAuckland1000: "Kiwi",
    AchievementAuckland1000Desc: "Verdiene in einem einzigen Durchlauf 1000 Schweizer Franken in Auckland",
    ExternalManageYourSave: "Spielstand im- oder exportieren",
    ExternalManageYourSaveDesc:
        "Aufgrund technischer Einschränkungen muss das Importieren und Exportieren deines Spielstands auf der offiziellen Website des Spiels erfolgen",
    MREPlant: "Meal, Ready-To-Eat Plant",
    PlayerTradeTaxCreditProduction: "Steuergutschrift: Produktion",
    PlayerTradeTaxCreditProductionDescV2:
        "Diese Steuergutschrift basiert auf der Menge an %{res}, die du seit der letzten Marktaktualisierung produziert hast. Du hast %{produziert} produziert und %{used} gehandelt",
    PlayerTradeTaxCreditMarketCap: "Steuergutschrift: Marktobergrenze",
    PlayerTradeTaxCreditMarketCapDesc:
        "Diese Steuergutschrift beträgt %{percentage} deiner Marktkapitalisierung, kann über Swiss Upgrade/Boost verbessert werden. Der Gesamtbetrag des Guthabens beträgt %{total}, davon hast du %{used} verwendet",
    PlayerTradeGrossTradeValue: "Bruttohandelswert",
    PlayerTradeTaxableValue: "Steuerwert",
    PlayerTradeTaxRate: "Steuersatz",
    PlayerTradeTaxRateDesc:
        "Der Steuersatz basiert auf der Preisdifferenz zwischen dem lokalen Preis und diesem Handel - der Steuersatz ist progressiv. 0 % ~ 50 %: 0,5 % für jeden Unterschied von 1 %; 50 % ~ 75 %: 1 % für jeden Unterschied von 1 %; 75 % ~ 100 %: 2 % für je 1 % Unterschied",
    PlayerTradeTaxPayable: "Zu zahlende Steuern",
    PlayerTradeTradeValueAfterTax: "Handelswert nach Steuern",
    PlayerTradeShowTaxCalculation: "Steuerberechnung anzeigen",
    PlayerTradeHideTaxCalculation: "Steuerberechnung ausblenden",
    PlayerTradeMaxTaxCreditValue: "Stelle den Betrag so ein, dass er der Steuergutschrift entspricht",
    WaterProductionx2: "Hochdruckwasserpumpe",
    WaterProductionx2Desc: "Wasserpumpen erbringen bei verdoppeltem Energieverbrauch den doppelten Ertrag",
    InputBufferTypeAuto: "Autom.",
    InputBufferTypeStockpile: "Vorrat",
    InputBuffer: "Ressourceneingangsverzögerung",
    InputBufferDesc:
        "The maximum cycles of input resource to keep in the storage before this building will no longer transport that resource. Auto means using prediction to keep a minimum buffer that allows continuous production. Stockpile means always transporting input resources regardless of the amount in the storage",
    InputCapacityOverride: "Input Capacity Override",
    InputCapacityOverrideDesc: "For each production cycle, transport %{percent} of the resources needed for production",
};
